(define (fma r1 s r2)
  (map (lambda (e1 e2)
	 (+ e1 (* s e2)))
       r1 r2))

(let ((v1 '(1 2 3 4))
      (v2 '(9 8 7 6)))
  (display v1)
  (write-string " + 3* ")
  (display v2)
  (write-string " -> ")
  (display (fma v1 3 v2))
  (newline)
  (display v1)
  (write-string " - 2* ")
  (display v2)
  (write-string " -> ")
  (display (fma v1 -2 v2))
  (newline))
