(define (dn val)
  (display val)
  (newline))

(dn (list 'b 'e 'h))
(dn (map (lambda (v) (cadr v)) (list (list 'a 'b) (list 'd 'e) (list 'g 'h))))
(dn (map cadr (list (list 'a 'b) (list 'd 'e) (list 'g 'h))))
(dn (map (if (even? (epochtime)) cadr car)
	 (list (list 'a 'b) (list 'd 'e) (list 'g 'h))))
(newline)
(dn '(b e h))
(dn (map (lambda (v) (cadr v)) '((a b) (d e) (g h))))
(dn (map cadr '((a b) (d e) (g h))))
(dn (map (if (even? (epochtime)) cadr car)
	 '((a b) (d e) (g h))))
