// Generated by wile, the extremely stable scheming genius compiler

#include "wile-rtl1.h"
#include "wile-rtl2.h"

// declarations

extern lval var_argv;
extern lval var_cmd_name;
extern lval var_stdin;
extern lval var_stdout;
extern lval var_stderr;
extern lval var_pi;
extern lval var_euler_gamma;
extern lval var_show_sign;
extern lval var_int_base;
extern lval var_flt_base;
extern lval var_flt_precision;
#include "wile-rtl2.h"
static lval fn_4(lptr*, lptr, const char*);

// definitions

// @@@ lambda (lst acc) @@@ bld-rtl-dir/wile-rtl2-000042.scm:14 @@@ fn_4 @@@
static lval fn_4(lptr* var_5, lptr var_6, const char* cloc)
{
lbl_7:;
lval var_8;
lval var_9;
var_9 = LVI_BOOL(true);
lval var_11;
var_11 = LVI_BOOL(var_6[0].vt == LV_NIL);
lval var_12;
var_12 = LVI_BOOL(LV_IS_FALSE(var_11));
var_9 = var_12;
if (LV_IS_FALSE(var_9)) {
goto lbl_10;
}
lval var_13;
#ifdef WILE_DO_CHECK
if (var_6[0].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000042.scm:16", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_13 = (var_6[0].v.pair.car ? *(var_6[0].v.pair.car) : LVI_NIL());
lval var_14;
{
lval var_15[1];
var_15[0] = var_13;
var_14 = wile_gen_list(1, var_15, NULL);
}
lval var_16;
{
lval var_17[2];
var_17[0] = V_CLOS(var_5,0);
var_17[1] = var_14;
var_16 = wile_gen_list(2, var_17, NULL);
}
var_16 = wile_apply_function(&(var_16), "bld-rtl-dir/wile-rtl2-000042.scm:16");
var_9 = var_16;
if (LV_IS_FALSE(var_9)) {
goto lbl_10;
}
lbl_10:;
if (LV_IS_FALSE(var_9)) {
lval var_18;
{
lval var_19[8];
var_19[0] = var_6[1];
var_18 = wile_list_reverse(NULL, var_19, "bld-rtl-dir/wile-rtl2-000042.scm:18");
}
var_8 = var_18;
} else {
lval var_20;
#ifdef WILE_DO_CHECK
if (var_6[0].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000042.scm:17", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_20 = (var_6[0].v.pair.cdr ? *(var_6[0].v.pair.cdr) : LVI_NIL());
lval var_21;
#ifdef WILE_DO_CHECK
if (var_6[0].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000042.scm:17", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_21 = (var_6[0].v.pair.car ? *(var_6[0].v.pair.car) : LVI_NIL());
lval var_22;
{
lptr p1 = NULL, p2 = NULL;
if (var_21.vt != LV_NIL) {
p1 = new_lv(LV_NIL);
*p1 = var_21;
}
if (var_6[1].vt != LV_NIL) {
p2 = new_lv(LV_NIL);
*p2 = var_6[1];
}
var_22 = LVI_PAIR(p1, p2);
}
lval var_23;
lval var_25[8];
var_25[0] = var_20;
var_25[1] = var_22;
var_6[0] = var_25[0];
var_6[1] = var_25[1];
goto lbl_7;
var_8 = var_23;
}
return var_8;
}
// end of lambda fn_4

// @@@ (list-take-while keep? lst) @@@ bld-rtl-dir/wile-rtl2-000042.scm:13 @@@ wile_list_take_while @@@
lval wile_list_take_while(lptr* var_1, lptr var_2, const char* cloc)
{
MK_CLOS(var_5,1);
lptr var_26 = new_lv(VT_UNINIT);
var_26->v.pair.car = &(var_2[0]);
P_CLOS(var_5,0) = var_26;
lval var_27;
var_27 = LVI_NIL();
lval var_28;
lval var_29[8];
var_29[0] = var_2[1];
var_29[1] = var_27;
var_28 = fn_4(var_5, var_29, "bld-rtl-dir/wile-rtl2-000042.scm:14");
*var_26 = var_2[0];
return var_28;
}
// end of function wile_list_take_while
