// Generated by wile, the extremely stable scheming genius compiler

#include "wile-rtl1.h"
#include "wile-rtl2.h"

// declarations

extern lval var_argv;
extern lval var_cmd_name;
extern lval var_stdin;
extern lval var_stdout;
extern lval var_stderr;
extern lval var_pi;
extern lval var_euler_gamma;
extern lval var_show_sign;
extern lval var_int_base;
extern lval var_flt_base;
extern lval var_flt_precision;
#include "wile-rtl2.h"
static lval fn_1(lptr*, lptr, const char*);
static lval fn_5(lptr*, lptr, const char*);
static lval fn_37(lptr*, lptr, const char*);
static lval fn_42(lptr*, lptr, const char*);

// definitions

// @@@ lambda (l acc) @@@ bld-rtl-dir/wile-rtl2-000027.scm:12 @@@ fn_5 @@@
static lval fn_5(lptr* var_6, lptr var_7, const char* cloc)
{
lbl_8:;
lval var_9;
lval var_10;
var_10 = LVI_BOOL(false);
lval var_12;
var_12 = LVI_BOOL(var_7[0].vt == LV_NIL);
var_10 = var_12;
if (!LV_IS_FALSE(var_10)) {
goto lbl_11;
}
lval var_13;
if (var_7[0].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000027.scm:14", "input is not a pair!");
}
var_13 = (var_7[0].v.pair.car ? *(var_7[0].v.pair.car) : LVI_NIL());
lval var_14;
{
lval var_15[1];
var_15[0] = var_13;
var_14 = wile_gen_list(1, var_15, NULL);
}
lval var_16;
{
lval var_17[2];
var_17[0] = V_CLOS(var_6,0);
var_17[1] = var_14;
var_16 = wile_gen_list(2, var_17, NULL);
}
var_16 = wile_apply_function(&(var_16), "bld-rtl-dir/wile-rtl2-000027.scm:14");
lval var_18;
var_18 = LVI_BOOL(LV_IS_FALSE(var_16));
var_10 = var_18;
if (!LV_IS_FALSE(var_10)) {
goto lbl_11;
}
lbl_11:;
if (LV_IS_FALSE(var_10)) {
lval var_19;
if (var_7[0].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000027.scm:16", "input is not a pair!");
}
var_19 = (var_7[0].v.pair.cdr ? *(var_7[0].v.pair.cdr) : LVI_NIL());
lval var_20;
if (var_7[0].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000027.scm:16", "input is not a pair!");
}
var_20 = (var_7[0].v.pair.car ? *(var_7[0].v.pair.car) : LVI_NIL());
lval var_21;
{
lptr p1 = NULL, p2 = NULL;
if (var_20.vt != LV_NIL) {
p1 = new_lv(LV_NIL);
*p1 = var_20;
}
if (var_7[1].vt != LV_NIL) {
p2 = new_lv(LV_NIL);
*p2 = var_7[1];
}
var_21 = LVI_PAIR(p1, p2);
}
lval var_22;
lval var_24[8];
var_24[0] = var_19;
var_24[1] = var_21;
var_7[0] = var_24[0];
var_7[1] = var_24[1];
goto lbl_8;
var_9 = var_22;
} else {
lval var_25;
{
lval var_26[8];
var_26[0] = var_7[1];
var_25 = wile_list_reverse(NULL, var_26, "bld-rtl-dir/wile-rtl2-000027.scm:15");
}
lval var_27;
{
lval var_28[2];
var_28[0] = var_25;
var_28[1] = var_7[0];
var_27 = wile_gen_list(2, var_28, NULL);
}
var_9 = var_27;
}
return var_9;
}
// end of lambda fn_5

// @@@ (list-keep-head keep? lst) @@@ bld-rtl-dir/wile-rtl2-000027.scm:11 @@@ fn_1 @@@
static lval fn_1(lptr* var_2, lptr var_3, const char* cloc)
{
MK_CLOS(var_6,1);
lptr var_29 = new_lv(VT_UNINIT);
var_29->v.pair.car = &(var_3[0]);
P_CLOS(var_6,0) = var_29;
lval var_30;
var_30 = LVI_NIL();
lval var_31;
lval var_32[8];
var_32[0] = var_3[1];
var_32[1] = var_30;
var_31 = fn_5(var_6, var_32, "bld-rtl-dir/wile-rtl2-000027.scm:12");
*var_29 = var_3[0];
return var_31;
}
// end of function fn_1

// @@@ lambda (c) @@@ bld-rtl-dir/wile-rtl2-000027.scm:23 @@@ fn_42 @@@
static lval fn_42(lptr* var_43, lptr var_44, const char* cloc)
{
lval var_46;
{
lval var_47[1];
var_47[0] = var_44[0];
var_46 = wile_gen_list(1, var_47, NULL);
}
lval var_48;
{
lval var_49[2];
var_49[0] = V_CLOS(var_43,0);
var_49[1] = var_46;
var_48 = wile_gen_list(2, var_49, NULL);
}
var_48 = wile_apply_function(&(var_48), "bld-rtl-dir/wile-rtl2-000027.scm:23");
lval var_50;
var_50 = LVI_BOOL(LV_IS_FALSE(var_48));
return var_50;
}
// end of lambda fn_42

// @@@ lambda (l a) @@@ bld-rtl-dir/wile-rtl2-000027.scm:21 @@@ fn_37 @@@
static lval fn_37(lptr* var_38, lptr var_39, const char* cloc)
{
lbl_40:;
lval var_41;
MK_CLOS(var_43,1);
lptr var_51 = new_lv(VT_UNINIT);
var_51->v.pair.car = &(V_CLOS(var_38,0));
P_CLOS(var_43,0) = var_51;
lval var_52;
lval var_53[8];
var_53[0] = LVI_PROC(fn_42,var_43,1);
var_53[1] = var_39[0];
var_52 = fn_1(NULL, var_53, "bld-rtl-dir/wile-rtl2-000027.scm:23");
var_41 = var_52;
lval var_55;
lval var_56;
var_56 = LVI_STRING("cadr");
lval var_57;
{
char* cp = strchr(var_56.v.str, 'r');
var_57 = var_41;
while (*(--cp) != 'c') {
if (var_57.vt != LV_PAIR) {
wile_exception("cxr", "bld-rtl-dir/wile-rtl2-000027.scm:24", "input does not have the right structure!");
}
if (*cp == 'a') {
var_57 = (var_57.v.pair.car ? *(var_57.v.pair.car) : LVI_NIL());
} else if (*cp == 'd') {
var_57 = (var_57.v.pair.cdr ? *(var_57.v.pair.cdr) : LVI_NIL());
} else {
wile_exception("cxr", "bld-rtl-dir/wile-rtl2-000027.scm:24", "got malformed control string '%s'", var_56.v.str);
}
}
}
lval var_58;
{
lval var_59[8];
var_59[0] = V_CLOS(var_38,0);
var_59[1] = var_57;
var_58 = wile_list_drop_while(NULL, var_59, "bld-rtl-dir/wile-rtl2-000027.scm:24");
}
var_55 = var_58;
lval var_60;
lval var_61;
if (var_41.vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000027.scm:25", "input is not a pair!");
}
var_61 = (var_41.v.pair.car ? *(var_41.v.pair.car) : LVI_NIL());
lval var_62;
{
lval var_64[1];
var_64[0] = var_61;
var_62 = wile_gen_list(1, var_64, NULL);
}
{
lval var_63[8];
var_63[0] = var_62;
var_62 = wile_char2string(NULL, var_63, "bld-rtl-dir/wile-rtl2-000027.scm:25");
}
lval var_65;
{
lptr p1 = NULL, p2 = NULL;
if (var_62.vt != LV_NIL) {
p1 = new_lv(LV_NIL);
*p1 = var_62;
}
if (var_39[1].vt != LV_NIL) {
p2 = new_lv(LV_NIL);
*p2 = var_39[1];
}
var_65 = LVI_PAIR(p1, p2);
}
var_60 = var_65;
lval var_66;
lval var_67;
var_67 = LVI_BOOL(var_55.vt == LV_NIL);
if (LV_IS_FALSE(var_67)) {
lval var_68;
lval var_70[8];
var_70[0] = var_55;
var_70[1] = var_60;
var_39[0] = var_70[0];
var_39[1] = var_70[1];
goto lbl_40;
var_66 = var_68;
} else {
lval var_71;
{
lval var_72[8];
var_72[0] = var_60;
var_71 = wile_list_reverse(NULL, var_72, "bld-rtl-dir/wile-rtl2-000027.scm:27");
}
var_66 = var_71;
}
*var_51 = V_CLOS(var_38,0);
return var_66;
}
// end of lambda fn_37

// @@@ (string-split-by drop? str) @@@ bld-rtl-dir/wile-rtl2-000027.scm:20 @@@ wile_string_split_by @@@
lval wile_string_split_by(lptr* var_34, lptr var_35, const char* cloc)
{
MK_CLOS(var_38,1);
lptr var_73 = new_lv(VT_UNINIT);
var_73->v.pair.car = &(var_35[0]);
P_CLOS(var_38,0) = var_73;
lval var_74;
{
lval var_75[8];
var_75[0] = var_35[1];
var_74 = wile_string2list(NULL, var_75, "bld-rtl-dir/wile-rtl2-000027.scm:21");
}
lval var_76;
{
lval var_77[8];
var_77[0] = var_35[0];
var_77[1] = var_74;
var_76 = wile_list_drop_while(NULL, var_77, "bld-rtl-dir/wile-rtl2-000027.scm:21");
}
lval var_78;
var_78 = LVI_NIL();
lval var_79;
lval var_80[8];
var_80[0] = var_76;
var_80[1] = var_78;
var_79 = fn_37(var_38, var_80, "bld-rtl-dir/wile-rtl2-000027.scm:21");
*var_73 = var_35[0];
return var_79;
}
// end of function wile_string_split_by

// @@@ char-whitespace? @@@ bld-rtl-dir/wile-rtl2-000027.scm:33 @@@ fn_85 @@@
static lval fn_85(lptr* var_86, lptr var_87, const char* cloc)
{
lval var_89;
var_89 = LVI_BOOL(isspace(var_87[0].v.chr));
return var_89;
}
// end of prim fn_85

// @@@ (string-split-by-whitespace str) @@@ bld-rtl-dir/wile-rtl2-000027.scm:32 @@@ wile_string_split_by_whitespace @@@
lval wile_string_split_by_whitespace(lptr* var_82, lptr var_83, const char* cloc)
{
lval var_90;
lval var_92[8];
var_92[0] = LVI_PROC(fn_85,NULL,1);
var_92[1] = var_83[0];
var_83[0] = var_92[0];
var_83[1] = var_92[1];
TAIL_CALL wile_string_split_by(NULL, var_83, "bld-rtl-dir/wile-rtl2-000027.scm:33");
return var_90;
}
// end of function wile_string_split_by_whitespace
