// Generated by wile, the extremely stable scheming genius compiler

#include "wile-rtl1.h"
#include "wile-rtl2.h"

// declarations

extern lval var_argv;
extern lval var_cmd_name;
extern lval var_stdin;
extern lval var_stdout;
extern lval var_stderr;
extern lval var_pi;
extern lval var_euler_gamma;
extern lval var_show_sign;
extern lval var_int_base;
extern lval var_flt_base;
extern lval var_flt_precision;
#include "wile-rtl2.h"
static lval fn_5(lptr*, lptr, const char*);
static lval fn_34(lptr*, lptr, const char*);
static lval fn_42(lptr*, lptr, const char*);
static lval fn_50(lptr*, lptr, const char*);

// definitions

// @@@ lambda (n) @@@ bld-rtl-dir/wile-rtl2-000084.scm:40 @@@ fn_5 @@@
static lval fn_5(lptr* var_6, lptr var_7, const char* cloc)
{
lval var_9;
lval var_10;
var_10 = LVI_BOOL(var_7[0].vt == LV_NIL);
if (LV_IS_FALSE(var_10)) {
lval var_11;
var_11 = wile_num2string(var_7[0], 10, INT_MIN, "bld-rtl-dir/wile-rtl2-000084.scm:40");
var_9 = var_11;
} else {
lval var_12;
var_12 = LVI_STRING("");
var_9 = var_12;
}
return var_9;
}
// end of lambda fn_5

// @@@ max/i @@@ bld-rtl-dir/wile-rtl2-000084.scm:42 @@@ fn_16 @@@
static lval fn_16(lptr* var_17, lptr var_18, const char* cloc)
{
lval var_20;
var_20 = LVI_INT((var_18[0].v.iv > var_18[1].v.iv) ? var_18[0].v.iv : var_18[1].v.iv);
return var_20;
}
// end of prim fn_16

// @@@ string-length @@@ bld-rtl-dir/wile-rtl2-000084.scm:42 @@@ fn_22 @@@
static lval fn_22(lptr* var_23, lptr var_24, const char* cloc)
{
lval var_26;
var_26 = LVI_INT(strlen(var_24[0].v.str));
return var_26;
}
// end of prim fn_22

// @@@ lambda (s) @@@ bld-rtl-dir/wile-rtl2-000084.scm:43 @@@ fn_34 @@@
static lval fn_34(lptr* var_35, lptr var_36, const char* cloc)
{
lval var_38;
var_38 = LVI_CHAR(32);
lval var_39;
{
lval var_40[8];
var_40[0] = var_36[0];
var_40[1] = var_38;
var_40[2] = V_CLOS(var_35,0);
var_39 = wile_string_pad_left(NULL, var_40, "bld-rtl-dir/wile-rtl2-000084.scm:43");
}
return var_39;
}
// end of lambda fn_34

// @@@ string-join-by @@@ bld-rtl-dir/wile-rtl2-000084.scm:52 @@@ fn_73 @@@
static lval fn_73(lptr* var_74, lptr var_75, const char* cloc)
{
lval var_77;
var_77 = var_75[1];
{
lval var_78[8];
var_78[0] = var_75[0];
var_78[1] = var_77;
var_77 = wile_string_join_by(NULL, var_78, "bld-rtl-dir/wile-rtl2-000084.scm:52");
}
return var_77;
}
// end of prim fn_73

// @@@ lambda (ic acc-c) @@@ bld-rtl-dir/wile-rtl2-000084.scm:49 @@@ fn_50 @@@
static lval fn_50(lptr* var_51, lptr var_52, const char* cloc)
{
lbl_53:;
lval var_54;
lval var_55;
switch (TYPE_COMBO(var_52[0].vt,V_CLOS(var_51,0).vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_55 = LVI_BOOL(var_52[0].v.iv >= V_CLOS(var_51,0).v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_55 = LVI_BOOL(var_52[0].v.iv * V_CLOS(var_51,0).v.irv.den >= V_CLOS(var_51,0).v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_55 = LVI_BOOL(var_52[0].v.iv >= V_CLOS(var_51,0).v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_55 = LVI_BOOL(var_52[0].v.irv.num >= V_CLOS(var_51,0).v.iv * var_52[0].v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_55 = LVI_BOOL(var_52[0].v.irv.num * V_CLOS(var_51,0).v.irv.den >= V_CLOS(var_51,0).v.irv.num * var_52[0].v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_55 = LVI_BOOL(var_52[0].v.irv.num >= V_CLOS(var_51,0).v.rv * var_52[0].v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_55 = LVI_BOOL(var_52[0].v.rv >= V_CLOS(var_51,0).v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_55 = LVI_BOOL(var_52[0].v.rv * V_CLOS(var_51,0).v.irv.den >= V_CLOS(var_51,0).v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_55 = LVI_BOOL(var_52[0].v.rv >= V_CLOS(var_51,0).v.rv);
break;
default:
wile_exception(">=", "bld-rtl-dir/wile-rtl2-000084.scm:51", "inputs are not real-valued numbers");
break;
}
if (LV_IS_FALSE(var_55)) {
lval var_56;
lval var_57;
if (LV_IS_FALSE(V_CLOS(var_51,1))) {
lval var_58;
var_58 = LVI_INT(V_CLOS(var_51,2).v.iv * V_CLOS(var_51,0).v.iv);
lval var_59;
var_59 = LVI_INT(var_52[0].v.iv + var_58.v.iv);
var_57 = var_59;
} else {
lval var_60;
var_60 = LVI_INT(var_52[0].v.iv * V_CLOS(var_51,3).v.iv);
lval var_61;
var_61 = LVI_INT(V_CLOS(var_51,2).v.iv + var_60.v.iv);
var_57 = var_61;
}
var_56 = var_57;
lval var_62;
var_62 = LVI_INT(1);
lval var_63;
var_63 = LVI_INT(var_52[0].v.iv + var_62.v.iv);
lval var_64;
{
if (V_CLOS(var_51,5).vt != LV_VECTOR) {
wile_exception("vector-ref", "bld-rtl-dir/wile-rtl2-000084.scm:57", "input is not a vector");
}
if (var_56.vt != LV_INT || var_56.v.iv < 0 || (size_t) var_56.v.iv >= V_CLOS(var_51,5).v.vec.capa) {
wile_exception("vector-ref", "bld-rtl-dir/wile-rtl2-000084.scm:57", "got bad index value");
}
var_64 = V_CLOS(var_51,5).v.vec.arr[var_56.v.iv] ? *(V_CLOS(var_51,5).v.vec.arr[var_56.v.iv]) : LVI_NIL();
}
lval var_65;
{
lval var_66[1];
var_66[0] = var_64;
var_65 = wile_gen_list(1, var_66, NULL);
}
lval var_67;
{
lval var_68[2];
var_68[0] = V_CLOS(var_51,4);
var_68[1] = var_65;
var_67 = wile_gen_list(2, var_68, NULL);
}
var_67 = wile_apply_function(&(var_67), "bld-rtl-dir/wile-rtl2-000084.scm:57");
lval var_69;
{
lptr p1 = NULL, p2 = NULL;
if (var_67.vt != LV_NIL) {
p1 = new_lv(LV_NIL);
*p1 = var_67;
}
if (var_52[1].vt != LV_NIL) {
p2 = new_lv(LV_NIL);
*p2 = var_52[1];
}
var_69 = LVI_PAIR(p1, p2);
}
lval var_70;
lval var_72[8];
var_72[0] = var_63;
var_72[1] = var_69;
var_52[0] = var_72[0];
var_52[1] = var_72[1];
goto lbl_53;
var_54 = var_70;
} else {
lval var_79;
var_79 = LVI_STRING(" ");
lval var_80;
{
lval var_81[8];
var_81[0] = var_52[1];
var_80 = wile_list_reverse(NULL, var_81, "bld-rtl-dir/wile-rtl2-000084.scm:52");
}
lval var_82;
{
lval var_83[3];
var_83[0] = LVI_PROC(fn_73,NULL,-2);
var_83[1] = var_79;
var_83[2] = var_80;
var_82 = wile_gen_list(3, var_83, NULL);
}
var_82 = wile_apply_function(&(var_82), "bld-rtl-dir/wile-rtl2-000084.scm:52");
var_54 = var_82;
}
return var_54;
}
// end of lambda fn_50

// @@@ lambda (ir acc-r) @@@ bld-rtl-dir/wile-rtl2-000084.scm:44 @@@ fn_42 @@@
static lval fn_42(lptr* var_43, lptr var_44, const char* cloc)
{
lbl_45:;
lval var_46;
lval var_47;
switch (TYPE_COMBO(var_44[0].vt,V_CLOS(var_43,0).vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_47 = LVI_BOOL(var_44[0].v.iv >= V_CLOS(var_43,0).v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_47 = LVI_BOOL(var_44[0].v.iv * V_CLOS(var_43,0).v.irv.den >= V_CLOS(var_43,0).v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_47 = LVI_BOOL(var_44[0].v.iv >= V_CLOS(var_43,0).v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_47 = LVI_BOOL(var_44[0].v.irv.num >= V_CLOS(var_43,0).v.iv * var_44[0].v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_47 = LVI_BOOL(var_44[0].v.irv.num * V_CLOS(var_43,0).v.irv.den >= V_CLOS(var_43,0).v.irv.num * var_44[0].v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_47 = LVI_BOOL(var_44[0].v.irv.num >= V_CLOS(var_43,0).v.rv * var_44[0].v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_47 = LVI_BOOL(var_44[0].v.rv >= V_CLOS(var_43,0).v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_47 = LVI_BOOL(var_44[0].v.rv * V_CLOS(var_43,0).v.irv.den >= V_CLOS(var_43,0).v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_47 = LVI_BOOL(var_44[0].v.rv >= V_CLOS(var_43,0).v.rv);
break;
default:
wile_exception(">=", "bld-rtl-dir/wile-rtl2-000084.scm:46", "inputs are not real-valued numbers");
break;
}
if (LV_IS_FALSE(var_47)) {
lval var_48;
var_48 = LVI_INT(1);
lval var_49;
var_49 = LVI_INT(var_44[0].v.iv + var_48.v.iv);
MK_CLOS(var_51,6);
lptr var_84 = new_lv(VT_UNINIT);
var_84->v.pair.car = &(V_CLOS(var_43,4));
P_CLOS(var_51,5) = var_84;
lptr var_85 = new_lv(VT_UNINIT);
var_85->v.pair.car = &(V_CLOS(var_43,3));
P_CLOS(var_51,4) = var_85;
lptr var_86 = new_lv(VT_UNINIT);
var_86->v.pair.car = &(V_CLOS(var_43,0));
P_CLOS(var_51,3) = var_86;
lptr var_87 = new_lv(VT_UNINIT);
var_87->v.pair.car = &(var_44[0]);
P_CLOS(var_51,2) = var_87;
lptr var_88 = new_lv(VT_UNINIT);
var_88->v.pair.car = &(V_CLOS(var_43,2));
P_CLOS(var_51,1) = var_88;
lptr var_89 = new_lv(VT_UNINIT);
var_89->v.pair.car = &(V_CLOS(var_43,1));
P_CLOS(var_51,0) = var_89;
lval var_90;
var_90 = LVI_INT(0);
lval var_91;
var_91 = LVI_NIL();
lval var_92;
lval var_93[8];
var_93[0] = var_90;
var_93[1] = var_91;
var_92 = fn_50(var_51, var_93, "bld-rtl-dir/wile-rtl2-000084.scm:49");
*var_84 = V_CLOS(var_43,4);
*var_85 = V_CLOS(var_43,3);
*var_89 = V_CLOS(var_43,1);
*var_86 = V_CLOS(var_43,0);
*var_87 = var_44[0];
*var_88 = V_CLOS(var_43,2);
lval var_95;
{
lptr p1 = NULL, p2 = NULL;
if (var_92.vt != LV_NIL) {
p1 = new_lv(LV_NIL);
*p1 = var_92;
}
if (var_44[1].vt != LV_NIL) {
p2 = new_lv(LV_NIL);
*p2 = var_44[1];
}
var_95 = LVI_PAIR(p1, p2);
}
lval var_96;
lval var_98[8];
var_98[0] = var_49;
var_98[1] = var_95;
var_44[0] = var_98[0];
var_44[1] = var_98[1];
goto lbl_45;
var_46 = var_96;
} else {
lval var_99;
{
lval var_100[8];
var_100[0] = var_44[1];
var_99 = wile_list_reverse(NULL, var_100, "bld-rtl-dir/wile-rtl2-000084.scm:47");
}
var_46 = var_99;
}
return var_46;
}
// end of lambda fn_42

// @@@ (matrix-print mat n-rows n-cols tr) @@@ bld-rtl-dir/wile-rtl2-000084.scm:39 @@@ wile_matrix_print @@@
lval wile_matrix_print(lptr* var_1, lptr var_2, const char* cloc)
{
lval var_4;
MK_CLOS(var_6,0);
lval var_13;
var_13 = LVI_NIL();
{
lval var_14[8];
var_14[0] = LVI_PROC(fn_5,var_6,1);
var_14[1] = var_2[0];
var_14[2] = var_13;
var_13 = wile_vector_map(NULL, var_14, "bld-rtl-dir/wile-rtl2-000084.scm:40");
}
var_4 = var_13;
lval var_15;
lval var_21;
var_21 = LVI_INT(0);
lval var_27;
{
lval var_28[8];
var_28[0] = var_4;
var_27 = wile_vector2list(NULL, var_28, "bld-rtl-dir/wile-rtl2-000084.scm:42");
}
lval var_29;
var_29 = LVI_NIL();
{
lval var_30[8];
var_30[0] = LVI_PROC(fn_22,NULL,1);
var_30[1] = var_27;
var_30[2] = var_29;
var_29 = wile_map(NULL, var_30, "bld-rtl-dir/wile-rtl2-000084.scm:42");
}
lval var_31;
{
lval var_32[8];
var_32[0] = LVI_PROC(fn_16,NULL,2);
var_32[1] = var_21;
var_32[2] = var_29;
var_31 = wile_foldl(NULL, var_32, "bld-rtl-dir/wile-rtl2-000084.scm:42");
}
var_15 = var_31;
lval var_33;
MK_CLOS(var_35,1);
lptr var_41 = new_lv(VT_UNINIT);
var_41->v.pair.car = &(var_15);
P_CLOS(var_35,0) = var_41;
var_33 = LVI_PROC(fn_34,var_35,1);
MK_CLOS(var_43,5);
lptr var_101 = new_lv(VT_UNINIT);
var_101->v.pair.car = &(var_4);
P_CLOS(var_43,4) = var_101;
lptr var_102 = new_lv(VT_UNINIT);
var_102->v.pair.car = &(var_33);
P_CLOS(var_43,3) = var_102;
lptr var_103 = new_lv(VT_UNINIT);
var_103->v.pair.car = &(var_2[3]);
P_CLOS(var_43,2) = var_103;
lptr var_104 = new_lv(VT_UNINIT);
var_104->v.pair.car = &(var_2[2]);
P_CLOS(var_43,1) = var_104;
lptr var_105 = new_lv(VT_UNINIT);
var_105->v.pair.car = &(var_2[1]);
P_CLOS(var_43,0) = var_105;
lval var_106;
var_106 = LVI_INT(0);
lval var_107;
var_107 = LVI_NIL();
lval var_108;
lval var_109[8];
var_109[0] = var_106;
var_109[1] = var_107;
var_108 = fn_42(var_43, var_109, "bld-rtl-dir/wile-rtl2-000084.scm:44");
*var_101 = var_4;
*var_105 = var_2[1];
*var_102 = var_33;
*var_104 = var_2[2];
*var_103 = var_2[3];
*var_41 = var_15;
return var_108;
}
// end of function wile_matrix_print
