// Generated by wile, the extremely stable scheming genius compiler

#include "wile-rtl1.h"
#include "wile-rtl2.h"

// declarations

extern lval var_argv;
extern lval var_cmd_name;
extern lval var_stdin;
extern lval var_stdout;
extern lval var_stderr;
extern lval var_pi;
extern lval var_euler_gamma;
extern lval var_show_sign;
extern lval var_int_base;
extern lval var_flt_base;
extern lval var_flt_precision;
#include "wile-rtl2.h"

// definitions

// @@@ (list->bytevector lst) @@@ bld-rtl-dir/wile-rtl2-000018.scm:13 @@@ wile_list2bytevector @@@
lval wile_list2bytevector(lptr* var_1, lptr var_2, const char* cloc)
{
lval var_4;
lval var_5;
{
lval var_6[8];
var_6[0] = var_2[0];
// bld-rtl-dir/wile-rtl2-000018.scm:14
var_5 = wile_list_length(NULL, var_6, "bld-rtl-dir/wile-rtl2-000018.scm:14");
}
var_4 = var_5;
lval var_7;
lval var_8;
{
size_t i, capa;
var_8.vt = LV_BVECTOR;
var_8.origin = var_4.origin;
capa = var_4.v.iv;
var_8.v.bvec.capa = capa;
var_8.v.bvec.arr = LISP_ALLOC(unsigned char, (capa > 0 ? capa : 1));
for (i = 0; i < capa; ++i) {
var_8.v.bvec.arr[i] = 0;
}
}
var_7 = var_8;
lval var_10;
lval var_12;
lval var_14;
var_14 = LVI_INT(0);
var_10 = var_14;
lval var_11;
lval var_13;
var_11 = var_2[0];
lval var_9;
lptr var_15 = new_lv(VT_UNINIT);
var_15->v.pair.car = &(var_10); // i
lptr var_16 = new_lv(VT_UNINIT);
var_16->v.pair.car = &(var_11); // lp
do {
lval var_17;
switch (TYPE_COMBO(var_10.vt,var_4.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_17 = LVI_BOOL(var_10.v.iv == var_4.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_17 = LVI_BOOL(var_10.v.iv * var_4.v.irv.den == var_4.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_17 = LVI_BOOL(var_10.v.iv == var_4.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_17 = LVI_BOOL(var_10.v.irv.num == var_4.v.iv * var_10.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_17 = LVI_BOOL(var_10.v.irv.num * var_4.v.irv.den == var_4.v.irv.num * var_10.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_17 = LVI_BOOL(var_10.v.irv.num == var_4.v.rv * var_10.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_17 = LVI_BOOL(var_10.v.rv == var_4.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_17 = LVI_BOOL(var_10.v.rv * var_4.v.irv.den == var_4.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_17 = LVI_BOOL(var_10.v.rv == var_4.v.rv);
break;
default:
WILE_EX("==", "inputs are not real-valued numbers");
break;
}
if (!LV_IS_FALSE(var_17)) {
var_9 = var_7;
break;
}
lval var_18;
lval var_19;
if (var_11.vt != LV_PAIR) {
WILE_EX("car", "input is not a pair!");
}
var_19 = (var_11.v.pair.car ? *(var_11.v.pair.car) : LVI_NIL());
var_18 = var_19;
lval var_21;
var_21 = LVI_BOOL(false);
do {
lval var_22;
var_22 = LVI_BOOL(var_18.vt == LV_CHAR);
var_21 = var_22;
if (!LV_IS_FALSE(var_21)) { break; }
lval var_23;
var_23 = LVI_BOOL(true);
do {
lval var_24;
var_24 = LVI_BOOL(var_18.vt == LV_INT);
var_23 = var_24;
if (LV_IS_FALSE(var_23)) { break; }
lval var_25;
var_25 = LVI_INT(0);
lval var_26;
switch (TYPE_COMBO(var_18.vt,var_25.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_26 = LVI_BOOL(var_18.v.iv >= var_25.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_26 = LVI_BOOL(var_18.v.iv * var_25.v.irv.den >= var_25.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_26 = LVI_BOOL(var_18.v.iv >= var_25.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_26 = LVI_BOOL(var_18.v.irv.num >= var_25.v.iv * var_18.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_26 = LVI_BOOL(var_18.v.irv.num * var_25.v.irv.den >= var_25.v.irv.num * var_18.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_26 = LVI_BOOL(var_18.v.irv.num >= var_25.v.rv * var_18.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_26 = LVI_BOOL(var_18.v.rv >= var_25.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_26 = LVI_BOOL(var_18.v.rv * var_25.v.irv.den >= var_25.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_26 = LVI_BOOL(var_18.v.rv >= var_25.v.rv);
break;
default:
WILE_EX(">=", "inputs are not real-valued numbers");
break;
}
var_23 = var_26;
if (LV_IS_FALSE(var_23)) { break; }
lval var_27;
var_27 = LVI_INT(256);
lval var_28;
switch (TYPE_COMBO(var_18.vt,var_27.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_28 = LVI_BOOL(var_18.v.iv < var_27.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_28 = LVI_BOOL(var_18.v.iv * var_27.v.irv.den < var_27.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_28 = LVI_BOOL(var_18.v.iv < var_27.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_28 = LVI_BOOL(var_18.v.irv.num < var_27.v.iv * var_18.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_28 = LVI_BOOL(var_18.v.irv.num * var_27.v.irv.den < var_27.v.irv.num * var_18.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_28 = LVI_BOOL(var_18.v.irv.num < var_27.v.rv * var_18.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_28 = LVI_BOOL(var_18.v.rv < var_27.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_28 = LVI_BOOL(var_18.v.rv * var_27.v.irv.den < var_27.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_28 = LVI_BOOL(var_18.v.rv < var_27.v.rv);
break;
default:
WILE_EX("<", "inputs are not real-valued numbers");
break;
}
var_23 = var_28;
if (LV_IS_FALSE(var_23)) { break; }
} while (0);
var_21 = var_23;
if (!LV_IS_FALSE(var_21)) { break; }
} while (0);
if (LV_IS_FALSE(var_21)) {
lval var_29;
var_29 = LVI_STRING("list->bytevector got a bad value");
lval var_30;
{
lval var_31[1];
var_31[0] = var_29;
var_30 = wile_gen_list(1, var_31, NULL);
}
if (var_30.vt == LV_PAIR && (var_30.v.pair.cdr == NULL || var_30.v.pair.cdr->vt == LV_NIL)) {
var_30 = (var_30.v.pair.car ? *(var_30.v.pair.car) : LVI_NIL());
}
cachalot->errval = new_lv(LV_NIL);
*(cachalot->errval) = var_30;
cachalot->l_whence = 0;
cachalot->c_whence = LISP_WHENCE;
longjmp(cachalot->cenv, 1);
} else {
{
if (var_7.vt != LV_BVECTOR) {
WILE_EX("bytevector-set!", "input is not a bytevector");
}
if (var_10.vt != LV_INT || var_10.v.iv < 0 || (size_t) var_10.v.iv >= var_7.v.bvec.capa) {
WILE_EX("bytevector-set!", "got bad index value");
}
if (!(var_18.vt == LV_CHAR || (var_18.vt == LV_INT && var_18.v.iv >= 0 && var_18.v.iv < 256))) {
WILE_EX("bytevector-set!", "got bad input value");
}
var_7.v.bvec.arr[var_10.v.iv] = (var_18.vt == LV_CHAR) ? var_18.v.chr : (unsigned char) var_18.v.iv;
}
}
lval var_33;
var_33 = LVI_INT(1);
lval var_34;
var_34 = LVI_INT(var_10.v.iv + var_33.v.iv);
var_12 = var_34;
lval var_35;
if (var_11.vt != LV_PAIR) {
WILE_EX("cdr", "input is not a pair!");
}
var_35 = (var_11.v.pair.cdr ? *(var_11.v.pair.cdr) : LVI_NIL());
var_13 = var_35;
var_10 = var_12;
var_11 = var_13;
} while (1);
*var_15 = var_10;
*var_16 = var_11;
return var_9;
}
// end of function wile_list2bytevector
