// Generated by wile, the extremely stable scheming genius compiler

#include "wile-rtl1.h"
#include "wile-rtl2.h"

// declarations

extern lval var_argv;
extern lval var_cmd_name;
extern lval var_stdin;
extern lval var_stdout;
extern lval var_stderr;
extern lval var_pi;
extern lval var_euler_gamma;
extern lval var_show_sign;
extern lval var_int_base;
extern lval var_flt_base;
extern lval var_flt_precision;
#include "wile-rtl2.h"

// definitions

// @@@ (expmod a n m) @@@ bld-rtl-dir/wile-rtl2-000025.scm:13 @@@ wile_expmod @@@
lval wile_expmod(lptr* var_1, lptr var_2, const char* cloc)
{
lbl_3:;
lval var_4;
lval var_6;
switch (var_2[1].vt) {
case LV_REAL:
var_6 = LVI_BOOL(var_2[1].v.rv < 0.0);
break;
case LV_RAT:
var_6 = LVI_BOOL((var_2[1].v.irv.num < 0 && var_2[1].v.irv.den >= 0) || (var_2[1].v.irv.num > 0 && var_2[1].v.irv.den < 0));
break;
case LV_INT:
var_6 = LVI_BOOL(var_2[1].v.iv < 0);
break;
default:
wile_exception("negative?", "bld-rtl-dir/wile-rtl2-000025.scm:14", "expects a real-valued number");
}
if (!LV_IS_FALSE(var_6)) {
lval var_7;
var_7 = LVI_BOOL(false);
var_4 = var_7;
goto lbl_5;
}
lval var_8;
switch (var_2[1].vt) {
case LV_REAL:
var_8 = LVI_BOOL(var_2[1].v.rv == 0.0);
break;
case LV_RAT:
var_8 = LVI_BOOL((var_2[1].v.irv.num == 0 && var_2[1].v.irv.den != 0));
break;
case LV_INT:
var_8 = LVI_BOOL(var_2[1].v.iv == 0);
break;
case LV_CMPLX:
var_8 = LVI_BOOL(CREAL(var_2[1].v.cv) == 0.0 && CIMAG(var_2[1].v.cv) == 0.0);
break;
default:
wile_exception("zero?", "bld-rtl-dir/wile-rtl2-000025.scm:15", "expects a real-valued number");
}
if (!LV_IS_FALSE(var_8)) {
lval var_9;
var_9 = LVI_INT(1);
lval var_10;
{
lisp_int_t nq, nr;
floor_qr(var_9.v.iv, var_2[2].v.iv, &nq, &nr, "bld-rtl-dir/wile-rtl2-000025.scm:15");
var_10 = LVI_INT(nr);
}
var_4 = var_10;
goto lbl_5;
}
lval var_11;
var_11 = LVI_BOOL((var_2[1].v.iv)%2 == 0);
if (!LV_IS_FALSE(var_11)) {
lval var_12;
var_12 = LVI_INT(var_2[0].v.iv * var_2[0].v.iv);
lval var_13;
{
lisp_int_t nq, nr;
floor_qr(var_12.v.iv, var_2[2].v.iv, &nq, &nr, "bld-rtl-dir/wile-rtl2-000025.scm:16");
var_13 = LVI_INT(nr);
}
lval var_14;
var_14 = LVI_INT(-1);
lval var_15;
var_15 = LVI_INT((var_14.v.iv >= 0) ? (var_2[1].v.iv << var_14.v.iv) : (var_2[1].v.iv >> -var_14.v.iv));
lval var_16;
lval var_18[8];
var_18[0] = var_13;
var_18[1] = var_15;
var_18[2] = var_2[2];
var_2[0] = var_18[0];
var_2[1] = var_18[1];
var_2[2] = var_18[2];
goto lbl_3;
var_4 = var_16;
goto lbl_5;
}
lval var_19;
var_19 = LVI_INT(1);
lval var_20;
var_20 = LVI_INT(var_2[1].v.iv - var_19.v.iv);
lval var_21;
lval var_22[8];
var_22[0] = var_2[0];
var_22[1] = var_20;
var_22[2] = var_2[2];
var_21 = wile_expmod(NULL, var_22, "bld-rtl-dir/wile-rtl2-000025.scm:17");
lval var_24;
var_24 = LVI_INT(var_2[0].v.iv * var_21.v.iv);
lval var_25;
{
lisp_int_t nq, nr;
floor_qr(var_24.v.iv, var_2[2].v.iv, &nq, &nr, "bld-rtl-dir/wile-rtl2-000025.scm:17");
var_25 = LVI_INT(nr);
}
var_4 = var_25;
lbl_5:;
return var_4;
}
// end of function wile_expmod
