// Generated by wile, the extremely stable scheming genius compiler

#include "wile-rtl1.h"
#include "wile-rtl2.h"

// declarations

extern lval var_argv;
extern lval var_cmd_name;
extern lval var_stdin;
extern lval var_stdout;
extern lval var_stderr;
extern lval var_pi;
extern lval var_euler_gamma;
extern lval var_show_sign;
extern lval var_int_base;
extern lval var_flt_base;
extern lval var_flt_precision;
#include "wile-rtl2.h"

// definitions

// @@@ (sqlite-meta-schema port tbl) @@@ bld-rtl-dir/wile-rtl2-000055.scm:13 @@@ wile_sql_meta_schema @@@
lval wile_sql_meta_schema(lptr* var_1, lptr var_2, const char* cloc)
{
lval var_4;
lval var_5;
var_5 = LVI_STRING("select sql from sqlite_schema where (name = ?1)");
lval var_6;
{
lval var_7[8];
var_7[0] = var_2[0];
var_7[1] = var_5;
// bld-rtl-dir/wile-rtl2-000055.scm:14
var_6 = wile_sql_stmt_prep(NULL, var_7, "bld-rtl-dir/wile-rtl2-000055.scm:14");
}
var_4 = var_6;
lval var_9;
{
lval var_11[1];
var_11[0] = var_2[1];
var_9 = wile_gen_list(1, var_11, NULL);
}
{
lval var_10[8];
var_10[0] = var_4;
var_10[1] = var_9;
// bld-rtl-dir/wile-rtl2-000055.scm:16
var_9 = wile_sql_stmt_bind(NULL, var_10, "bld-rtl-dir/wile-rtl2-000055.scm:16");
}
lval var_12;
lval var_13;
{
lval var_14[8];
var_14[0] = var_4;
// bld-rtl-dir/wile-rtl2-000055.scm:17
var_13 = wile_sql_stmt_run(NULL, var_14, "bld-rtl-dir/wile-rtl2-000055.scm:17");
}
var_12 = var_13;
{
lval var_16[8];
var_16[0] = var_4;
// bld-rtl-dir/wile-rtl2-000055.scm:18
(void)
 wile_sql_stmt_clean(NULL, var_16, "bld-rtl-dir/wile-rtl2-000055.scm:18");
}
lval var_17;
var_17 = LVI_STRING("caadr");
lval var_18;
{
char* cp = strchr(var_17.v.str, 'r');
var_18 = var_12;
while (*(--cp) != 'c') {
if (var_18.vt != LV_PAIR) {
WILE_EX("cxr", "input does not have the right structure!");
}
if (*cp == 'a') {
var_18 = (var_18.v.pair.car ? *(var_18.v.pair.car) : LVI_NIL());
} else if (*cp == 'd') {
var_18 = (var_18.v.pair.cdr ? *(var_18.v.pair.cdr) : LVI_NIL());
} else {
WILE_EX("cxr", "got malformed control string '%s'", var_17.v.str);
}
}
}
return var_18;
}
// end of function wile_sql_meta_schema
