// Generated by wile, the extremely stable scheming genius compiler

#include "wile-rtl1.h"
#include "wile-rtl2.h"

// declarations

extern lval var_argv;
extern lval var_cmd_name;
extern lval var_stdin;
extern lval var_stdout;
extern lval var_stderr;
extern lval var_pi;
extern lval var_euler_gamma;
extern lval var_show_sign;
extern lval var_int_base;
extern lval var_flt_base;
extern lval var_flt_precision;
#include "wile-rtl2.h"

// definitions

// @@@ (string-trim-left drop? str) @@@ bld-rtl-dir/wile-rtl2-000042.scm:13 @@@ wile_string_trim_left @@@
lval wile_string_trim_left(lptr* var_1, lptr var_2)
{
lval var_4;
{
lval vs[8];
vs[0] = var_2[1];
var_4 = wile_string2list(NULL, vs);
}
lval var_5;
{
lval vs[8];
vs[0] = var_2[0];
vs[1] = var_4;
var_5 = wile_list_drop_while(NULL, vs);
}
lval var_6;
{
lval vs[1];
vs[0] = var_5;
var_6 = gen_list(1, vs, NULL);
}
{
lval vs[8];
vs[0] = var_6;
var_6 = wile_char2string(NULL, vs);
}
return var_6;
}
// end of function wile_string_trim_left
