// Generated by wile, the extremely stable scheming genius compiler

#include "wile-rtl1.h"
#include "wile-rtl2.h"

// declarations

extern lval var_argv;
extern lval var_cmd_name;
extern lval var_stdin;
extern lval var_stdout;
extern lval var_stderr;
extern lval var_pi;
extern lval var_euler_gamma;
extern lval var_show_sign;
extern lval var_int_base;
extern lval var_flt_base;
extern lval var_flt_precision;
#include "wile-rtl2.h"

// definitions

// @@@ (list-unhead lst n) @@@ bld-rtl-dir/wile-rtl2-000012.scm:13 @@@ wile_list_unhead @@@
lval wile_list_unhead(lptr* var_1, lptr var_2)
{
lval var_4;
{
lval vs[8];
vs[0] = var_2[0];
var_4 = wile_list_length(NULL, vs);
}
lval var_5;
var_5 = LVI_INT(var_4.v.iv - var_2[1].v.iv);
lval var_6;
{
lval vs[8];
vs[0] = var_2[0];
vs[1] = var_5;
var_6 = wile_list_tail(NULL, vs);
}
return var_6;
}
// end of function wile_list_unhead
