// Generated by wile, the extremely stable scheming genius compiler

#include "wile-rtl1.h"
#include "wile-rtl2.h"

// declarations

extern lval var_argv;
extern lval var_cmd_name;
extern lval var_stdin;
extern lval var_stdout;
extern lval var_stderr;
extern lval var_pi;
extern lval var_euler_gamma;
extern lval var_show_sign;
extern lval var_int_base;
extern lval var_flt_base;
extern lval var_flt_precision;
#include "wile-rtl2.h"

// definitions

// @@@ (list-length lst) @@@ bld-rtl-dir/wile-rtl2-000001.scm:15 @@@ wile_list_length @@@
lval wile_list_length(lptr* var_1, lptr var_2, const char* cloc)
{
lval var_4;
lval var_5;
var_5 = LVI_INT(0);
var_4 = var_5;
lval var_6;
var_6 = var_2[0];
lval var_10;
lval var_11;
lval var_12;
var_12 = LVI_INT(0);
var_10 = var_12;
lptr var_13 = new_lv(VT_UNINIT);
var_13->v.pair.car = &(var_10);
lbl_8:
lval var_14;
var_14 = LVI_BOOL(var_6.vt == LV_NIL);
if (!LV_IS_FALSE(var_14)) {
goto lbl_9;
}
lval var_15;
var_15 = LVI_INT(1);
lval var_16;
var_16 = LVI_INT(var_4.v.iv + var_15.v.iv);
var_4 = var_16;
lval var_17;
if (var_6.vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000001.scm:20", "input is not a pair!");
}
var_17 = (var_6.v.pair.cdr ? *(var_6.v.pair.cdr) : LVI_NIL());
var_6 = var_17;
lval var_18;
var_18 = LVI_INT(1);
lval var_19;
var_19 = LVI_INT(var_10.v.iv + var_18.v.iv);
var_11 = var_19;
var_10 = var_11;
goto lbl_8;
lbl_9:;
*var_13 = var_10;
return var_4;
}
// end of function wile_list_length
