// Generated by wile, the extremely stable scheming genius compiler

#include "wile-rtl1.h"
#include "wile-rtl2.h"

// declarations

extern lval var_argv;
extern lval var_cmd_name;
extern lval var_stdin;
extern lval var_stdout;
extern lval var_stderr;
extern lval var_pi;
extern lval var_euler_gamma;
extern lval var_show_sign;
extern lval var_int_base;
extern lval var_flt_base;
extern lval var_flt_precision;
#include "wile-rtl2.h"
static lval fn_1(lptr*, lptr, const char*);
static lval fn_2(lptr*, lptr, const char*);
static lval fn_3(lptr*, lptr, const char*);
static lval fn_4(lptr*, lptr, const char*);
static lval fn_5(lptr*, lptr, const char*);
static lval fn_9(lptr*, lptr, const char*);
static lval fn_49(lptr*, lptr, const char*);
static lval fn_97(lptr*, lptr, const char*);
static lval fn_151(lptr*, lptr, const char*);
static lval fn_211(lptr*, lptr, const char*);
static lval fn_245(lptr*, lptr, const char*);

// definitions

// @@@ lambda (l1 acc) @@@ bld-rtl-dir/wile-rtl2-000029.scm:12 @@@ fn_9 @@@
static lval fn_9(lptr* var_10, lptr var_11, const char* cloc)
{
lbl_12:;
lval var_13;
lval var_14;
var_14 = LVI_BOOL(var_11[0].vt == LV_NIL);
if (LV_IS_FALSE(var_14)) {
lval var_15;
#ifdef WILE_DO_CHECK
if (var_11[0].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000029.scm:16", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_15 = (var_11[0].v.pair.cdr ? *(var_11[0].v.pair.cdr) : LVI_NIL());
lval var_16;
#ifdef WILE_DO_CHECK
if (var_11[0].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:16", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_16 = (var_11[0].v.pair.car ? *(var_11[0].v.pair.car) : LVI_NIL());
lval var_17;
{
lval var_18[1];
var_18[0] = var_16;
var_17 = wile_gen_list(1, var_18, NULL);
}
lval var_19;
{
lval var_20[2];
var_20[0] = V_CLOS(var_10,0);
var_20[1] = var_17;
var_19 = wile_gen_list(2, var_20, NULL);
}
var_19 = wile_apply_function(&(var_19), "bld-rtl-dir/wile-rtl2-000029.scm:16");
lval var_21;
{
lptr p1 = NULL, p2 = NULL;
if (var_19.vt != LV_NIL) {
p1 = new_lv(LV_NIL);
*p1 = var_19;
}
if (var_11[1].vt != LV_NIL) {
p2 = new_lv(LV_NIL);
*p2 = var_11[1];
}
var_21 = LVI_PAIR(p1, p2);
}
lval var_22;
lval var_24[8];
var_24[0] = var_15;
var_24[1] = var_21;
var_11[0] = var_24[0];
var_11[1] = var_24[1];
goto lbl_12;
var_13 = var_22;
} else {
lval var_25;
{
lval var_26[8];
var_26[0] = var_11[1];
var_25 = wile_list_reverse(NULL, var_26, "bld-rtl-dir/wile-rtl2-000029.scm:15");
}
var_13 = var_25;
}
return var_13;
}
// end of lambda fn_9

// @@@ (map1 proc lst) @@@ bld-rtl-dir/wile-rtl2-000029.scm:11 @@@ fn_1 @@@
static lval fn_1(lptr* var_6, lptr var_7, const char* cloc)
{
MK_CLOS(var_10,1);
lptr var_27 = new_lv(VT_UNINIT);
var_27->v.pair.car = &(var_7[0]);
P_CLOS(var_10,0) = var_27;
lval var_28;
var_28 = LVI_NIL();
lval var_29;
lval var_30[8];
var_30[0] = var_7[1];
var_30[1] = var_28;
var_29 = fn_9(var_10, var_30, "bld-rtl-dir/wile-rtl2-000029.scm:12");
*var_27 = var_7[0];
return var_29;
}
// end of function fn_1

// @@@ lambda (l1 l2 acc) @@@ bld-rtl-dir/wile-rtl2-000029.scm:22 @@@ fn_49 @@@
static lval fn_49(lptr* var_50, lptr var_51, const char* cloc)
{
lbl_52:;
lval var_53;
lval var_54;
var_54 = LVI_BOOL(var_51[0].vt == LV_NIL);
if (LV_IS_FALSE(var_54)) {
lval var_55;
#ifdef WILE_DO_CHECK
if (var_51[0].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000029.scm:27", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_55 = (var_51[0].v.pair.cdr ? *(var_51[0].v.pair.cdr) : LVI_NIL());
lval var_56;
#ifdef WILE_DO_CHECK
if (var_51[1].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000029.scm:28", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_56 = (var_51[1].v.pair.cdr ? *(var_51[1].v.pair.cdr) : LVI_NIL());
lval var_57;
#ifdef WILE_DO_CHECK
if (var_51[0].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:29", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_57 = (var_51[0].v.pair.car ? *(var_51[0].v.pair.car) : LVI_NIL());
lval var_58;
#ifdef WILE_DO_CHECK
if (var_51[1].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:29", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_58 = (var_51[1].v.pair.car ? *(var_51[1].v.pair.car) : LVI_NIL());
lval var_59;
{
lval var_60[2];
var_60[0] = var_57;
var_60[1] = var_58;
var_59 = wile_gen_list(2, var_60, NULL);
}
lval var_61;
{
lval var_62[2];
var_62[0] = V_CLOS(var_50,0);
var_62[1] = var_59;
var_61 = wile_gen_list(2, var_62, NULL);
}
var_61 = wile_apply_function(&(var_61), "bld-rtl-dir/wile-rtl2-000029.scm:29");
lval var_63;
{
lptr p1 = NULL, p2 = NULL;
if (var_61.vt != LV_NIL) {
p1 = new_lv(LV_NIL);
*p1 = var_61;
}
if (var_51[2].vt != LV_NIL) {
p2 = new_lv(LV_NIL);
*p2 = var_51[2];
}
var_63 = LVI_PAIR(p1, p2);
}
lval var_64;
lval var_66[8];
var_66[0] = var_55;
var_66[1] = var_56;
var_66[2] = var_63;
var_51[0] = var_66[0];
var_51[1] = var_66[1];
var_51[2] = var_66[2];
goto lbl_52;
var_53 = var_64;
} else {
lval var_67;
{
lval var_68[8];
var_68[0] = var_51[2];
var_67 = wile_list_reverse(NULL, var_68, "bld-rtl-dir/wile-rtl2-000029.scm:26");
}
var_53 = var_67;
}
return var_53;
}
// end of lambda fn_49

// @@@ (map2 proc lst1 lst2) @@@ bld-rtl-dir/wile-rtl2-000029.scm:18 @@@ fn_2 @@@
static lval fn_2(lptr* var_32, lptr var_33, const char* cloc)
{
lval var_35;
lval var_36;
{
lval var_37[8];
var_37[0] = var_33[1];
var_36 = wile_list_length(NULL, var_37, "bld-rtl-dir/wile-rtl2-000029.scm:19");
}
var_35 = var_36;
lval var_38;
lval var_39;
{
lval var_40[8];
var_40[0] = var_33[2];
var_39 = wile_list_length(NULL, var_40, "bld-rtl-dir/wile-rtl2-000029.scm:20");
}
var_38 = var_39;
lval var_41;
lval var_42;
switch (TYPE_COMBO(var_35.vt,var_38.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_42 = LVI_BOOL(var_35.v.iv == var_38.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_42 = LVI_BOOL(var_35.v.iv * var_38.v.irv.den == var_38.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_42 = LVI_BOOL(var_35.v.iv == var_38.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_42 = LVI_BOOL(var_35.v.irv.num == var_38.v.iv * var_35.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_42 = LVI_BOOL(var_35.v.irv.num * var_38.v.irv.den == var_38.v.irv.num * var_35.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_42 = LVI_BOOL(var_35.v.irv.num == var_38.v.rv * var_35.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_42 = LVI_BOOL(var_35.v.rv == var_38.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_42 = LVI_BOOL(var_35.v.rv * var_38.v.irv.den == var_38.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_42 = LVI_BOOL(var_35.v.rv == var_38.v.rv);
break;
default:
wile_exception("==", "bld-rtl-dir/wile-rtl2-000029.scm:21", "inputs are not real-valued numbers");
break;
}
if (LV_IS_FALSE(var_42)) {
lval var_43;
var_43 = LVI_STRING("map: list lengths differ %d %d");
lval var_44;
{
lval var_46[2];
var_46[0] = var_35;
var_46[1] = var_38;
var_44 = wile_gen_list(2, var_46, NULL);
}
{
lval var_45[8];
var_45[0] = var_43;
var_45[1] = var_44;
var_44 = wile_sprintf(NULL, var_45, "bld-rtl-dir/wile-rtl2-000029.scm:31");
}
lval var_47;
{
lval var_48[1];
var_48[0] = var_44;
var_47 = wile_gen_list(1, var_48, NULL);
}
if (var_47.vt == LV_PAIR && (var_47.v.pair.cdr == NULL || var_47.v.pair.cdr->vt == LV_NIL)) {
var_47 = (var_47.v.pair.car ? *(var_47.v.pair.car) : LVI_NIL());
}
cachalot->errval = new_lv(LV_NIL);
*(cachalot->errval) = var_47;
cachalot->whence = "bld-rtl-dir/wile-rtl2-000029.scm:31";
longjmp(cachalot->cenv, 1);
var_41 = var_47;
} else {
MK_CLOS(var_50,1);
lptr var_69 = new_lv(VT_UNINIT);
var_69->v.pair.car = &(var_33[0]);
P_CLOS(var_50,0) = var_69;
lval var_70;
var_70 = LVI_NIL();
lval var_71;
lval var_72[8];
var_72[0] = var_33[1];
var_72[1] = var_33[2];
var_72[2] = var_70;
var_71 = fn_49(var_50, var_72, "bld-rtl-dir/wile-rtl2-000029.scm:22");
*var_69 = var_33[0];
var_41 = var_71;
}
return var_41;
}
// end of function fn_2

// @@@ lambda (l1 l2 l3 acc) @@@ bld-rtl-dir/wile-rtl2-000029.scm:38 @@@ fn_97 @@@
static lval fn_97(lptr* var_98, lptr var_99, const char* cloc)
{
lbl_100:;
lval var_101;
lval var_102;
var_102 = LVI_BOOL(var_99[0].vt == LV_NIL);
if (LV_IS_FALSE(var_102)) {
lval var_103;
#ifdef WILE_DO_CHECK
if (var_99[0].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000029.scm:44", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_103 = (var_99[0].v.pair.cdr ? *(var_99[0].v.pair.cdr) : LVI_NIL());
lval var_104;
#ifdef WILE_DO_CHECK
if (var_99[1].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000029.scm:45", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_104 = (var_99[1].v.pair.cdr ? *(var_99[1].v.pair.cdr) : LVI_NIL());
lval var_105;
#ifdef WILE_DO_CHECK
if (var_99[2].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000029.scm:46", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_105 = (var_99[2].v.pair.cdr ? *(var_99[2].v.pair.cdr) : LVI_NIL());
lval var_106;
#ifdef WILE_DO_CHECK
if (var_99[0].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:47", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_106 = (var_99[0].v.pair.car ? *(var_99[0].v.pair.car) : LVI_NIL());
lval var_107;
#ifdef WILE_DO_CHECK
if (var_99[1].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:47", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_107 = (var_99[1].v.pair.car ? *(var_99[1].v.pair.car) : LVI_NIL());
lval var_108;
#ifdef WILE_DO_CHECK
if (var_99[2].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:47", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_108 = (var_99[2].v.pair.car ? *(var_99[2].v.pair.car) : LVI_NIL());
lval var_109;
{
lval var_110[3];
var_110[0] = var_106;
var_110[1] = var_107;
var_110[2] = var_108;
var_109 = wile_gen_list(3, var_110, NULL);
}
lval var_111;
{
lval var_112[2];
var_112[0] = V_CLOS(var_98,0);
var_112[1] = var_109;
var_111 = wile_gen_list(2, var_112, NULL);
}
var_111 = wile_apply_function(&(var_111), "bld-rtl-dir/wile-rtl2-000029.scm:47");
lval var_113;
{
lptr p1 = NULL, p2 = NULL;
if (var_111.vt != LV_NIL) {
p1 = new_lv(LV_NIL);
*p1 = var_111;
}
if (var_99[3].vt != LV_NIL) {
p2 = new_lv(LV_NIL);
*p2 = var_99[3];
}
var_113 = LVI_PAIR(p1, p2);
}
lval var_114;
lval var_116[8];
var_116[0] = var_103;
var_116[1] = var_104;
var_116[2] = var_105;
var_116[3] = var_113;
var_99[0] = var_116[0];
var_99[1] = var_116[1];
var_99[2] = var_116[2];
var_99[3] = var_116[3];
goto lbl_100;
var_101 = var_114;
} else {
lval var_117;
{
lval var_118[8];
var_118[0] = var_99[3];
var_117 = wile_list_reverse(NULL, var_118, "bld-rtl-dir/wile-rtl2-000029.scm:43");
}
var_101 = var_117;
}
return var_101;
}
// end of lambda fn_97

// @@@ (map3 proc lst1 lst2 lst3) @@@ bld-rtl-dir/wile-rtl2-000029.scm:33 @@@ fn_3 @@@
static lval fn_3(lptr* var_74, lptr var_75, const char* cloc)
{
lval var_77;
lval var_78;
{
lval var_79[8];
var_79[0] = var_75[1];
var_78 = wile_list_length(NULL, var_79, "bld-rtl-dir/wile-rtl2-000029.scm:34");
}
var_77 = var_78;
lval var_80;
lval var_81;
{
lval var_82[8];
var_82[0] = var_75[2];
var_81 = wile_list_length(NULL, var_82, "bld-rtl-dir/wile-rtl2-000029.scm:35");
}
var_80 = var_81;
lval var_83;
lval var_84;
{
lval var_85[8];
var_85[0] = var_75[3];
var_84 = wile_list_length(NULL, var_85, "bld-rtl-dir/wile-rtl2-000029.scm:36");
}
var_83 = var_84;
lval var_86;
lval var_87;
var_87 = LVI_BOOL(true);
lval var_89;
switch (TYPE_COMBO(var_77.vt,var_80.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_89 = LVI_BOOL(var_77.v.iv == var_80.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_89 = LVI_BOOL(var_77.v.iv * var_80.v.irv.den == var_80.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_89 = LVI_BOOL(var_77.v.iv == var_80.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_89 = LVI_BOOL(var_77.v.irv.num == var_80.v.iv * var_77.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_89 = LVI_BOOL(var_77.v.irv.num * var_80.v.irv.den == var_80.v.irv.num * var_77.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_89 = LVI_BOOL(var_77.v.irv.num == var_80.v.rv * var_77.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_89 = LVI_BOOL(var_77.v.rv == var_80.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_89 = LVI_BOOL(var_77.v.rv * var_80.v.irv.den == var_80.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_89 = LVI_BOOL(var_77.v.rv == var_80.v.rv);
break;
default:
wile_exception("==", "bld-rtl-dir/wile-rtl2-000029.scm:37", "inputs are not real-valued numbers");
break;
}
var_87 = var_89;
if (LV_IS_FALSE(var_87)) {
goto lbl_88;
}
lval var_90;
switch (TYPE_COMBO(var_77.vt,var_83.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_90 = LVI_BOOL(var_77.v.iv == var_83.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_90 = LVI_BOOL(var_77.v.iv * var_83.v.irv.den == var_83.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_90 = LVI_BOOL(var_77.v.iv == var_83.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_90 = LVI_BOOL(var_77.v.irv.num == var_83.v.iv * var_77.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_90 = LVI_BOOL(var_77.v.irv.num * var_83.v.irv.den == var_83.v.irv.num * var_77.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_90 = LVI_BOOL(var_77.v.irv.num == var_83.v.rv * var_77.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_90 = LVI_BOOL(var_77.v.rv == var_83.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_90 = LVI_BOOL(var_77.v.rv * var_83.v.irv.den == var_83.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_90 = LVI_BOOL(var_77.v.rv == var_83.v.rv);
break;
default:
wile_exception("==", "bld-rtl-dir/wile-rtl2-000029.scm:37", "inputs are not real-valued numbers");
break;
}
var_87 = var_90;
if (LV_IS_FALSE(var_87)) {
goto lbl_88;
}
lbl_88:;
if (LV_IS_FALSE(var_87)) {
lval var_91;
var_91 = LVI_STRING("map: list lengths differ %d %d %d");
lval var_92;
{
lval var_94[3];
var_94[0] = var_77;
var_94[1] = var_80;
var_94[2] = var_83;
var_92 = wile_gen_list(3, var_94, NULL);
}
{
lval var_93[8];
var_93[0] = var_91;
var_93[1] = var_92;
var_92 = wile_sprintf(NULL, var_93, "bld-rtl-dir/wile-rtl2-000029.scm:49");
}
lval var_95;
{
lval var_96[1];
var_96[0] = var_92;
var_95 = wile_gen_list(1, var_96, NULL);
}
if (var_95.vt == LV_PAIR && (var_95.v.pair.cdr == NULL || var_95.v.pair.cdr->vt == LV_NIL)) {
var_95 = (var_95.v.pair.car ? *(var_95.v.pair.car) : LVI_NIL());
}
cachalot->errval = new_lv(LV_NIL);
*(cachalot->errval) = var_95;
cachalot->whence = "bld-rtl-dir/wile-rtl2-000029.scm:49";
longjmp(cachalot->cenv, 1);
var_86 = var_95;
} else {
MK_CLOS(var_98,1);
lptr var_119 = new_lv(VT_UNINIT);
var_119->v.pair.car = &(var_75[0]);
P_CLOS(var_98,0) = var_119;
lval var_120;
var_120 = LVI_NIL();
lval var_121;
lval var_122[8];
var_122[0] = var_75[1];
var_122[1] = var_75[2];
var_122[2] = var_75[3];
var_122[3] = var_120;
var_121 = fn_97(var_98, var_122, "bld-rtl-dir/wile-rtl2-000029.scm:38");
*var_119 = var_75[0];
var_86 = var_121;
}
return var_86;
}
// end of function fn_3

// @@@ lambda (l1 l2 l3 l4 acc) @@@ bld-rtl-dir/wile-rtl2-000029.scm:57 @@@ fn_151 @@@
static lval fn_151(lptr* var_152, lptr var_153, const char* cloc)
{
lbl_154:;
lval var_155;
lval var_156;
var_156 = LVI_BOOL(var_153[0].vt == LV_NIL);
if (LV_IS_FALSE(var_156)) {
lval var_157;
#ifdef WILE_DO_CHECK
if (var_153[0].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000029.scm:64", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_157 = (var_153[0].v.pair.cdr ? *(var_153[0].v.pair.cdr) : LVI_NIL());
lval var_158;
#ifdef WILE_DO_CHECK
if (var_153[1].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000029.scm:65", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_158 = (var_153[1].v.pair.cdr ? *(var_153[1].v.pair.cdr) : LVI_NIL());
lval var_159;
#ifdef WILE_DO_CHECK
if (var_153[2].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000029.scm:66", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_159 = (var_153[2].v.pair.cdr ? *(var_153[2].v.pair.cdr) : LVI_NIL());
lval var_160;
#ifdef WILE_DO_CHECK
if (var_153[3].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000029.scm:67", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_160 = (var_153[3].v.pair.cdr ? *(var_153[3].v.pair.cdr) : LVI_NIL());
lval var_161;
#ifdef WILE_DO_CHECK
if (var_153[0].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:68", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_161 = (var_153[0].v.pair.car ? *(var_153[0].v.pair.car) : LVI_NIL());
lval var_162;
#ifdef WILE_DO_CHECK
if (var_153[1].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:68", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_162 = (var_153[1].v.pair.car ? *(var_153[1].v.pair.car) : LVI_NIL());
lval var_163;
#ifdef WILE_DO_CHECK
if (var_153[2].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:68", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_163 = (var_153[2].v.pair.car ? *(var_153[2].v.pair.car) : LVI_NIL());
lval var_164;
#ifdef WILE_DO_CHECK
if (var_153[3].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:68", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_164 = (var_153[3].v.pair.car ? *(var_153[3].v.pair.car) : LVI_NIL());
lval var_165;
{
lval var_166[4];
var_166[0] = var_161;
var_166[1] = var_162;
var_166[2] = var_163;
var_166[3] = var_164;
var_165 = wile_gen_list(4, var_166, NULL);
}
lval var_167;
{
lval var_168[2];
var_168[0] = V_CLOS(var_152,0);
var_168[1] = var_165;
var_167 = wile_gen_list(2, var_168, NULL);
}
var_167 = wile_apply_function(&(var_167), "bld-rtl-dir/wile-rtl2-000029.scm:68");
lval var_169;
{
lptr p1 = NULL, p2 = NULL;
if (var_167.vt != LV_NIL) {
p1 = new_lv(LV_NIL);
*p1 = var_167;
}
if (var_153[4].vt != LV_NIL) {
p2 = new_lv(LV_NIL);
*p2 = var_153[4];
}
var_169 = LVI_PAIR(p1, p2);
}
lval var_170;
lval var_172[8];
var_172[0] = var_157;
var_172[1] = var_158;
var_172[2] = var_159;
var_172[3] = var_160;
var_172[4] = var_169;
var_153[0] = var_172[0];
var_153[1] = var_172[1];
var_153[2] = var_172[2];
var_153[3] = var_172[3];
var_153[4] = var_172[4];
goto lbl_154;
var_155 = var_170;
} else {
lval var_173;
{
lval var_174[8];
var_174[0] = var_153[4];
var_173 = wile_list_reverse(NULL, var_174, "bld-rtl-dir/wile-rtl2-000029.scm:63");
}
var_155 = var_173;
}
return var_155;
}
// end of lambda fn_151

// @@@ (map4 proc lst1 lst2 lst3 lst4) @@@ bld-rtl-dir/wile-rtl2-000029.scm:51 @@@ fn_4 @@@
static lval fn_4(lptr* var_124, lptr var_125, const char* cloc)
{
lval var_127;
lval var_128;
{
lval var_129[8];
var_129[0] = var_125[1];
var_128 = wile_list_length(NULL, var_129, "bld-rtl-dir/wile-rtl2-000029.scm:52");
}
var_127 = var_128;
lval var_130;
lval var_131;
{
lval var_132[8];
var_132[0] = var_125[2];
var_131 = wile_list_length(NULL, var_132, "bld-rtl-dir/wile-rtl2-000029.scm:53");
}
var_130 = var_131;
lval var_133;
lval var_134;
{
lval var_135[8];
var_135[0] = var_125[3];
var_134 = wile_list_length(NULL, var_135, "bld-rtl-dir/wile-rtl2-000029.scm:54");
}
var_133 = var_134;
lval var_136;
lval var_137;
{
lval var_138[8];
var_138[0] = var_125[4];
var_137 = wile_list_length(NULL, var_138, "bld-rtl-dir/wile-rtl2-000029.scm:55");
}
var_136 = var_137;
lval var_139;
lval var_140;
var_140 = LVI_BOOL(true);
lval var_142;
switch (TYPE_COMBO(var_127.vt,var_130.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_142 = LVI_BOOL(var_127.v.iv == var_130.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_142 = LVI_BOOL(var_127.v.iv * var_130.v.irv.den == var_130.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_142 = LVI_BOOL(var_127.v.iv == var_130.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_142 = LVI_BOOL(var_127.v.irv.num == var_130.v.iv * var_127.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_142 = LVI_BOOL(var_127.v.irv.num * var_130.v.irv.den == var_130.v.irv.num * var_127.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_142 = LVI_BOOL(var_127.v.irv.num == var_130.v.rv * var_127.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_142 = LVI_BOOL(var_127.v.rv == var_130.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_142 = LVI_BOOL(var_127.v.rv * var_130.v.irv.den == var_130.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_142 = LVI_BOOL(var_127.v.rv == var_130.v.rv);
break;
default:
wile_exception("==", "bld-rtl-dir/wile-rtl2-000029.scm:56", "inputs are not real-valued numbers");
break;
}
var_140 = var_142;
if (LV_IS_FALSE(var_140)) {
goto lbl_141;
}
lval var_143;
switch (TYPE_COMBO(var_127.vt,var_133.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_143 = LVI_BOOL(var_127.v.iv == var_133.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_143 = LVI_BOOL(var_127.v.iv * var_133.v.irv.den == var_133.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_143 = LVI_BOOL(var_127.v.iv == var_133.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_143 = LVI_BOOL(var_127.v.irv.num == var_133.v.iv * var_127.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_143 = LVI_BOOL(var_127.v.irv.num * var_133.v.irv.den == var_133.v.irv.num * var_127.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_143 = LVI_BOOL(var_127.v.irv.num == var_133.v.rv * var_127.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_143 = LVI_BOOL(var_127.v.rv == var_133.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_143 = LVI_BOOL(var_127.v.rv * var_133.v.irv.den == var_133.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_143 = LVI_BOOL(var_127.v.rv == var_133.v.rv);
break;
default:
wile_exception("==", "bld-rtl-dir/wile-rtl2-000029.scm:56", "inputs are not real-valued numbers");
break;
}
var_140 = var_143;
if (LV_IS_FALSE(var_140)) {
goto lbl_141;
}
lval var_144;
switch (TYPE_COMBO(var_127.vt,var_136.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_144 = LVI_BOOL(var_127.v.iv == var_136.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_144 = LVI_BOOL(var_127.v.iv * var_136.v.irv.den == var_136.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_144 = LVI_BOOL(var_127.v.iv == var_136.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_144 = LVI_BOOL(var_127.v.irv.num == var_136.v.iv * var_127.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_144 = LVI_BOOL(var_127.v.irv.num * var_136.v.irv.den == var_136.v.irv.num * var_127.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_144 = LVI_BOOL(var_127.v.irv.num == var_136.v.rv * var_127.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_144 = LVI_BOOL(var_127.v.rv == var_136.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_144 = LVI_BOOL(var_127.v.rv * var_136.v.irv.den == var_136.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_144 = LVI_BOOL(var_127.v.rv == var_136.v.rv);
break;
default:
wile_exception("==", "bld-rtl-dir/wile-rtl2-000029.scm:56", "inputs are not real-valued numbers");
break;
}
var_140 = var_144;
if (LV_IS_FALSE(var_140)) {
goto lbl_141;
}
lbl_141:;
if (LV_IS_FALSE(var_140)) {
lval var_145;
var_145 = LVI_STRING("map: list lengths differ %d %d %d %d");
lval var_146;
{
lval var_148[4];
var_148[0] = var_127;
var_148[1] = var_130;
var_148[2] = var_133;
var_148[3] = var_136;
var_146 = wile_gen_list(4, var_148, NULL);
}
{
lval var_147[8];
var_147[0] = var_145;
var_147[1] = var_146;
var_146 = wile_sprintf(NULL, var_147, "bld-rtl-dir/wile-rtl2-000029.scm:70");
}
lval var_149;
{
lval var_150[1];
var_150[0] = var_146;
var_149 = wile_gen_list(1, var_150, NULL);
}
if (var_149.vt == LV_PAIR && (var_149.v.pair.cdr == NULL || var_149.v.pair.cdr->vt == LV_NIL)) {
var_149 = (var_149.v.pair.car ? *(var_149.v.pair.car) : LVI_NIL());
}
cachalot->errval = new_lv(LV_NIL);
*(cachalot->errval) = var_149;
cachalot->whence = "bld-rtl-dir/wile-rtl2-000029.scm:70";
longjmp(cachalot->cenv, 1);
var_139 = var_149;
} else {
MK_CLOS(var_152,1);
lptr var_175 = new_lv(VT_UNINIT);
var_175->v.pair.car = &(var_125[0]);
P_CLOS(var_152,0) = var_175;
lval var_176;
var_176 = LVI_NIL();
lval var_177;
lval var_178[8];
var_178[0] = var_125[1];
var_178[1] = var_125[2];
var_178[2] = var_125[3];
var_178[3] = var_125[4];
var_178[4] = var_176;
var_177 = fn_151(var_152, var_178, "bld-rtl-dir/wile-rtl2-000029.scm:57");
*var_175 = var_125[0];
var_139 = var_177;
}
return var_139;
}
// end of function fn_4

// @@@ lambda (l1 l2 l3 l4 l5 acc) @@@ bld-rtl-dir/wile-rtl2-000029.scm:80 @@@ fn_211 @@@
static lval fn_211(lptr* var_212, lptr var_213, const char* cloc)
{
lbl_214:;
lval var_215;
lval var_216;
var_216 = LVI_BOOL(var_213[0].vt == LV_NIL);
if (LV_IS_FALSE(var_216)) {
lval var_217;
#ifdef WILE_DO_CHECK
if (var_213[0].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000029.scm:88", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_217 = (var_213[0].v.pair.cdr ? *(var_213[0].v.pair.cdr) : LVI_NIL());
lval var_218;
#ifdef WILE_DO_CHECK
if (var_213[1].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000029.scm:89", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_218 = (var_213[1].v.pair.cdr ? *(var_213[1].v.pair.cdr) : LVI_NIL());
lval var_219;
#ifdef WILE_DO_CHECK
if (var_213[2].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000029.scm:90", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_219 = (var_213[2].v.pair.cdr ? *(var_213[2].v.pair.cdr) : LVI_NIL());
lval var_220;
#ifdef WILE_DO_CHECK
if (var_213[3].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000029.scm:91", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_220 = (var_213[3].v.pair.cdr ? *(var_213[3].v.pair.cdr) : LVI_NIL());
lval var_221;
#ifdef WILE_DO_CHECK
if (var_213[4].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000029.scm:92", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_221 = (var_213[4].v.pair.cdr ? *(var_213[4].v.pair.cdr) : LVI_NIL());
lval var_222;
#ifdef WILE_DO_CHECK
if (var_213[0].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:93", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_222 = (var_213[0].v.pair.car ? *(var_213[0].v.pair.car) : LVI_NIL());
lval var_223;
#ifdef WILE_DO_CHECK
if (var_213[1].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:93", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_223 = (var_213[1].v.pair.car ? *(var_213[1].v.pair.car) : LVI_NIL());
lval var_224;
#ifdef WILE_DO_CHECK
if (var_213[2].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:93", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_224 = (var_213[2].v.pair.car ? *(var_213[2].v.pair.car) : LVI_NIL());
lval var_225;
#ifdef WILE_DO_CHECK
if (var_213[3].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:93", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_225 = (var_213[3].v.pair.car ? *(var_213[3].v.pair.car) : LVI_NIL());
lval var_226;
#ifdef WILE_DO_CHECK
if (var_213[4].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:93", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_226 = (var_213[4].v.pair.car ? *(var_213[4].v.pair.car) : LVI_NIL());
lval var_227;
{
lval var_228[5];
var_228[0] = var_222;
var_228[1] = var_223;
var_228[2] = var_224;
var_228[3] = var_225;
var_228[4] = var_226;
var_227 = wile_gen_list(5, var_228, NULL);
}
lval var_229;
{
lval var_230[2];
var_230[0] = V_CLOS(var_212,0);
var_230[1] = var_227;
var_229 = wile_gen_list(2, var_230, NULL);
}
var_229 = wile_apply_function(&(var_229), "bld-rtl-dir/wile-rtl2-000029.scm:93");
lval var_231;
{
lptr p1 = NULL, p2 = NULL;
if (var_229.vt != LV_NIL) {
p1 = new_lv(LV_NIL);
*p1 = var_229;
}
if (var_213[5].vt != LV_NIL) {
p2 = new_lv(LV_NIL);
*p2 = var_213[5];
}
var_231 = LVI_PAIR(p1, p2);
}
lval var_232;
lval var_234[8];
var_234[0] = var_217;
var_234[1] = var_218;
var_234[2] = var_219;
var_234[3] = var_220;
var_234[4] = var_221;
var_234[5] = var_231;
var_213[0] = var_234[0];
var_213[1] = var_234[1];
var_213[2] = var_234[2];
var_213[3] = var_234[3];
var_213[4] = var_234[4];
var_213[5] = var_234[5];
goto lbl_214;
var_215 = var_232;
} else {
lval var_235;
{
lval var_236[8];
var_236[0] = var_213[5];
var_235 = wile_list_reverse(NULL, var_236, "bld-rtl-dir/wile-rtl2-000029.scm:87");
}
var_215 = var_235;
}
return var_215;
}
// end of lambda fn_211

// @@@ (map5 proc lst1 lst2 lst3 lst4 lst5) @@@ bld-rtl-dir/wile-rtl2-000029.scm:73 @@@ fn_5 @@@
static lval fn_5(lptr* var_180, lptr var_181, const char* cloc)
{
lval var_183;
lval var_184;
{
lval var_185[8];
var_185[0] = var_181[1];
var_184 = wile_list_length(NULL, var_185, "bld-rtl-dir/wile-rtl2-000029.scm:74");
}
var_183 = var_184;
lval var_186;
lval var_187;
{
lval var_188[8];
var_188[0] = var_181[2];
var_187 = wile_list_length(NULL, var_188, "bld-rtl-dir/wile-rtl2-000029.scm:75");
}
var_186 = var_187;
lval var_189;
lval var_190;
{
lval var_191[8];
var_191[0] = var_181[3];
var_190 = wile_list_length(NULL, var_191, "bld-rtl-dir/wile-rtl2-000029.scm:76");
}
var_189 = var_190;
lval var_192;
lval var_193;
{
lval var_194[8];
var_194[0] = var_181[4];
var_193 = wile_list_length(NULL, var_194, "bld-rtl-dir/wile-rtl2-000029.scm:77");
}
var_192 = var_193;
lval var_195;
lval var_196;
{
lval var_197[8];
var_197[0] = var_181[5];
var_196 = wile_list_length(NULL, var_197, "bld-rtl-dir/wile-rtl2-000029.scm:78");
}
var_195 = var_196;
lval var_198;
lval var_199;
var_199 = LVI_BOOL(true);
lval var_201;
switch (TYPE_COMBO(var_183.vt,var_186.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_201 = LVI_BOOL(var_183.v.iv == var_186.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_201 = LVI_BOOL(var_183.v.iv * var_186.v.irv.den == var_186.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_201 = LVI_BOOL(var_183.v.iv == var_186.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_201 = LVI_BOOL(var_183.v.irv.num == var_186.v.iv * var_183.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_201 = LVI_BOOL(var_183.v.irv.num * var_186.v.irv.den == var_186.v.irv.num * var_183.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_201 = LVI_BOOL(var_183.v.irv.num == var_186.v.rv * var_183.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_201 = LVI_BOOL(var_183.v.rv == var_186.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_201 = LVI_BOOL(var_183.v.rv * var_186.v.irv.den == var_186.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_201 = LVI_BOOL(var_183.v.rv == var_186.v.rv);
break;
default:
wile_exception("==", "bld-rtl-dir/wile-rtl2-000029.scm:79", "inputs are not real-valued numbers");
break;
}
var_199 = var_201;
if (LV_IS_FALSE(var_199)) {
goto lbl_200;
}
lval var_202;
switch (TYPE_COMBO(var_183.vt,var_189.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_202 = LVI_BOOL(var_183.v.iv == var_189.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_202 = LVI_BOOL(var_183.v.iv * var_189.v.irv.den == var_189.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_202 = LVI_BOOL(var_183.v.iv == var_189.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_202 = LVI_BOOL(var_183.v.irv.num == var_189.v.iv * var_183.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_202 = LVI_BOOL(var_183.v.irv.num * var_189.v.irv.den == var_189.v.irv.num * var_183.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_202 = LVI_BOOL(var_183.v.irv.num == var_189.v.rv * var_183.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_202 = LVI_BOOL(var_183.v.rv == var_189.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_202 = LVI_BOOL(var_183.v.rv * var_189.v.irv.den == var_189.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_202 = LVI_BOOL(var_183.v.rv == var_189.v.rv);
break;
default:
wile_exception("==", "bld-rtl-dir/wile-rtl2-000029.scm:79", "inputs are not real-valued numbers");
break;
}
var_199 = var_202;
if (LV_IS_FALSE(var_199)) {
goto lbl_200;
}
lval var_203;
switch (TYPE_COMBO(var_183.vt,var_192.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_203 = LVI_BOOL(var_183.v.iv == var_192.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_203 = LVI_BOOL(var_183.v.iv * var_192.v.irv.den == var_192.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_203 = LVI_BOOL(var_183.v.iv == var_192.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_203 = LVI_BOOL(var_183.v.irv.num == var_192.v.iv * var_183.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_203 = LVI_BOOL(var_183.v.irv.num * var_192.v.irv.den == var_192.v.irv.num * var_183.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_203 = LVI_BOOL(var_183.v.irv.num == var_192.v.rv * var_183.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_203 = LVI_BOOL(var_183.v.rv == var_192.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_203 = LVI_BOOL(var_183.v.rv * var_192.v.irv.den == var_192.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_203 = LVI_BOOL(var_183.v.rv == var_192.v.rv);
break;
default:
wile_exception("==", "bld-rtl-dir/wile-rtl2-000029.scm:79", "inputs are not real-valued numbers");
break;
}
var_199 = var_203;
if (LV_IS_FALSE(var_199)) {
goto lbl_200;
}
lval var_204;
switch (TYPE_COMBO(var_183.vt,var_195.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_204 = LVI_BOOL(var_183.v.iv == var_195.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_204 = LVI_BOOL(var_183.v.iv * var_195.v.irv.den == var_195.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_204 = LVI_BOOL(var_183.v.iv == var_195.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_204 = LVI_BOOL(var_183.v.irv.num == var_195.v.iv * var_183.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_204 = LVI_BOOL(var_183.v.irv.num * var_195.v.irv.den == var_195.v.irv.num * var_183.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_204 = LVI_BOOL(var_183.v.irv.num == var_195.v.rv * var_183.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_204 = LVI_BOOL(var_183.v.rv == var_195.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_204 = LVI_BOOL(var_183.v.rv * var_195.v.irv.den == var_195.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_204 = LVI_BOOL(var_183.v.rv == var_195.v.rv);
break;
default:
wile_exception("==", "bld-rtl-dir/wile-rtl2-000029.scm:79", "inputs are not real-valued numbers");
break;
}
var_199 = var_204;
if (LV_IS_FALSE(var_199)) {
goto lbl_200;
}
lbl_200:;
if (LV_IS_FALSE(var_199)) {
lval var_205;
var_205 = LVI_STRING("map: list lengths differ %d %d %d %d %d");
lval var_206;
{
lval var_208[5];
var_208[0] = var_183;
var_208[1] = var_186;
var_208[2] = var_189;
var_208[3] = var_192;
var_208[4] = var_195;
var_206 = wile_gen_list(5, var_208, NULL);
}
{
lval var_207[8];
var_207[0] = var_205;
var_207[1] = var_206;
var_206 = wile_sprintf(NULL, var_207, "bld-rtl-dir/wile-rtl2-000029.scm:95");
}
lval var_209;
{
lval var_210[1];
var_210[0] = var_206;
var_209 = wile_gen_list(1, var_210, NULL);
}
if (var_209.vt == LV_PAIR && (var_209.v.pair.cdr == NULL || var_209.v.pair.cdr->vt == LV_NIL)) {
var_209 = (var_209.v.pair.car ? *(var_209.v.pair.car) : LVI_NIL());
}
cachalot->errval = new_lv(LV_NIL);
*(cachalot->errval) = var_209;
cachalot->whence = "bld-rtl-dir/wile-rtl2-000029.scm:95";
longjmp(cachalot->cenv, 1);
var_198 = var_209;
} else {
MK_CLOS(var_212,1);
lptr var_237 = new_lv(VT_UNINIT);
var_237->v.pair.car = &(var_181[0]);
P_CLOS(var_212,0) = var_237;
lval var_238;
var_238 = LVI_NIL();
lval var_239;
lval var_240[8];
var_240[0] = var_181[1];
var_240[1] = var_181[2];
var_240[2] = var_181[3];
var_240[3] = var_181[4];
var_240[4] = var_181[5];
var_240[5] = var_238;
var_239 = fn_211(var_212, var_240, "bld-rtl-dir/wile-rtl2-000029.scm:80");
*var_237 = var_181[0];
var_198 = var_239;
}
return var_198;
}
// end of function fn_5

// @@@ car @@@ bld-rtl-dir/wile-rtl2-000029.scm:104 @@@ fn_252 @@@
static lval fn_252(lptr* var_253, lptr var_254, const char* cloc)
{
lval var_256;
#ifdef WILE_DO_CHECK
if (var_254[0].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:104", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_256 = (var_254[0].v.pair.car ? *(var_254[0].v.pair.car) : LVI_NIL());
return var_256;
}
// end of prim fn_252

// @@@ cdr @@@ bld-rtl-dir/wile-rtl2-000029.scm:104 @@@ fn_263 @@@
static lval fn_263(lptr* var_264, lptr var_265, const char* cloc)
{
lval var_267;
#ifdef WILE_DO_CHECK
if (var_265[0].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000029.scm:104", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_267 = (var_265[0].v.pair.cdr ? *(var_265[0].v.pair.cdr) : LVI_NIL());
return var_267;
}
// end of prim fn_263

// @@@ (m2 proc acc ls) @@@ bld-rtl-dir/wile-rtl2-000029.scm:101 @@@ fn_245 @@@
static lval fn_245(lptr* var_246, lptr var_247, const char* cloc)
{
lbl_248:;
lval var_249;
lval var_250;
#ifdef WILE_DO_CHECK
if (var_247[2].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:102", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_250 = (var_247[2].v.pair.car ? *(var_247[2].v.pair.car) : LVI_NIL());
lval var_251;
var_251 = LVI_BOOL(var_250.vt == LV_NIL);
if (LV_IS_FALSE(var_251)) {
lval var_257;
lval var_258[8];
var_258[0] = LVI_PROC(fn_252,NULL,1);
var_258[1] = var_247[2];
var_257 = fn_1(NULL, var_258, "bld-rtl-dir/wile-rtl2-000029.scm:104");
lval var_260;
{
lval var_261[2];
var_261[0] = var_247[0];
var_261[1] = var_257;
var_260 = wile_gen_list(2, var_261, NULL);
}
var_260 = wile_apply_function(&(var_260), "bld-rtl-dir/wile-rtl2-000029.scm:104");
lval var_262;
{
lptr p1 = NULL, p2 = NULL;
if (var_260.vt != LV_NIL) {
p1 = new_lv(LV_NIL);
*p1 = var_260;
}
if (var_247[1].vt != LV_NIL) {
p2 = new_lv(LV_NIL);
*p2 = var_247[1];
}
var_262 = LVI_PAIR(p1, p2);
}
lval var_268;
lval var_269[8];
var_269[0] = LVI_PROC(fn_263,NULL,1);
var_269[1] = var_247[2];
var_268 = fn_1(NULL, var_269, "bld-rtl-dir/wile-rtl2-000029.scm:104");
lval var_271;
lval var_273[8];
var_273[0] = var_247[0];
var_273[1] = var_262;
var_273[2] = var_268;
var_247[0] = var_273[0];
var_247[1] = var_273[1];
var_247[2] = var_273[2];
goto lbl_248;
var_249 = var_271;
} else {
lval var_274;
{
lval var_275[8];
var_275[0] = var_247[1];
var_274 = wile_list_reverse(NULL, var_275, "bld-rtl-dir/wile-rtl2-000029.scm:103");
}
var_249 = var_274;
}
return var_249;
}
// end of function fn_245

// @@@ list-length @@@ bld-rtl-dir/wile-rtl2-000029.scm:113 @@@ fn_313 @@@
static lval fn_313(lptr* var_314, lptr var_315, const char* cloc)
{
lval var_317;
{
lval var_318[8];
var_318[0] = var_315[0];
var_317 = wile_list_length(NULL, var_318, "bld-rtl-dir/wile-rtl2-000029.scm:113");
}
return var_317;
}
// end of prim fn_313

// @@@ min/i @@@ bld-rtl-dir/wile-rtl2-000029.scm:114 @@@ fn_323 @@@
static lval fn_323(lptr* var_324, lptr var_325, const char* cloc)
{
lval var_327;
var_327 = LVI_INT((var_325[0].v.iv < var_325[1].v.iv) ? var_325[0].v.iv : var_325[1].v.iv);
return var_327;
}
// end of prim fn_323

// @@@ max/i @@@ bld-rtl-dir/wile-rtl2-000029.scm:114 @@@ fn_330 @@@
static lval fn_330(lptr* var_331, lptr var_332, const char* cloc)
{
lval var_334;
var_334 = LVI_INT((var_332[0].v.iv > var_332[1].v.iv) ? var_332[0].v.iv : var_332[1].v.iv);
return var_334;
}
// end of prim fn_330

// @@@ (map proc lst . ls) @@@ bld-rtl-dir/wile-rtl2-000029.scm:100 @@@ wile_map @@@
lval wile_map(lptr* var_242, lptr var_243, const char* cloc)
{
lval var_276;
{
lval var_277[8];
var_277[0] = var_243[2];
var_276 = wile_list_length(NULL, var_277, "bld-rtl-dir/wile-rtl2-000029.scm:105");
}
lval var_278;
if (var_276.vt != LV_INT) {
wile_exception("case", "bld-rtl-dir/wile-rtl2-000029.scm:105", "case-value type does not match case type");
}
switch (var_276.v.iv) {
case 0:
{
lval var_279;
lval var_281[8];
var_281[0] = var_243[0];
var_281[1] = var_243[1];
var_243[0] = var_281[0];
var_243[1] = var_281[1];
TAIL_CALL fn_1(NULL, var_243, "bld-rtl-dir/wile-rtl2-000029.scm:107");
var_278 = var_279;
break;
}
case 1:
{
lval var_282;
#ifdef WILE_DO_CHECK
if (var_243[2].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:108", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_282 = (var_243[2].v.pair.car ? *(var_243[2].v.pair.car) : LVI_NIL());
lval var_283;
lval var_285[8];
var_285[0] = var_243[0];
var_285[1] = var_243[1];
var_285[2] = var_282;
var_243[0] = var_285[0];
var_243[1] = var_285[1];
var_243[2] = var_285[2];
TAIL_CALL fn_2(NULL, var_243, "bld-rtl-dir/wile-rtl2-000029.scm:108");
var_278 = var_283;
break;
}
case 2:
{
lval var_286;
#ifdef WILE_DO_CHECK
if (var_243[2].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:109", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_286 = (var_243[2].v.pair.car ? *(var_243[2].v.pair.car) : LVI_NIL());
lval var_287;
var_287 = LVI_STRING("cadr");
lval var_288;
{
char* cp = strchr(var_287.v.str, 'r');
var_288 = var_243[2];
while (*(--cp) != 'c') {
#ifdef WILE_DO_CHECK
if (var_288.vt != LV_PAIR) {
wile_exception("cxr", "bld-rtl-dir/wile-rtl2-000029.scm:109", "input does not have the right structure!");
}
#endif // WILE_DO_CHECK
if (*cp == 'a') {
var_288 = (var_288.v.pair.car ? *(var_288.v.pair.car) : LVI_NIL());
} else if (*cp == 'd') {
var_288 = (var_288.v.pair.cdr ? *(var_288.v.pair.cdr) : LVI_NIL());
} else {
wile_exception("cxr", "bld-rtl-dir/wile-rtl2-000029.scm:109", "got malformed control string '%s'", var_287.v.str);
}
}
}
lval var_289;
lval var_291[8];
var_291[0] = var_243[0];
var_291[1] = var_243[1];
var_291[2] = var_286;
var_291[3] = var_288;
var_243[0] = var_291[0];
var_243[1] = var_291[1];
var_243[2] = var_291[2];
var_243[3] = var_291[3];
TAIL_CALL fn_3(NULL, var_243, "bld-rtl-dir/wile-rtl2-000029.scm:109");
var_278 = var_289;
break;
}
case 3:
{
lval var_292;
#ifdef WILE_DO_CHECK
if (var_243[2].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:110", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_292 = (var_243[2].v.pair.car ? *(var_243[2].v.pair.car) : LVI_NIL());
lval var_293;
var_293 = LVI_STRING("cadr");
lval var_294;
{
char* cp = strchr(var_293.v.str, 'r');
var_294 = var_243[2];
while (*(--cp) != 'c') {
#ifdef WILE_DO_CHECK
if (var_294.vt != LV_PAIR) {
wile_exception("cxr", "bld-rtl-dir/wile-rtl2-000029.scm:110", "input does not have the right structure!");
}
#endif // WILE_DO_CHECK
if (*cp == 'a') {
var_294 = (var_294.v.pair.car ? *(var_294.v.pair.car) : LVI_NIL());
} else if (*cp == 'd') {
var_294 = (var_294.v.pair.cdr ? *(var_294.v.pair.cdr) : LVI_NIL());
} else {
wile_exception("cxr", "bld-rtl-dir/wile-rtl2-000029.scm:110", "got malformed control string '%s'", var_293.v.str);
}
}
}
lval var_295;
var_295 = LVI_STRING("caddr");
lval var_296;
{
char* cp = strchr(var_295.v.str, 'r');
var_296 = var_243[2];
while (*(--cp) != 'c') {
#ifdef WILE_DO_CHECK
if (var_296.vt != LV_PAIR) {
wile_exception("cxr", "bld-rtl-dir/wile-rtl2-000029.scm:110", "input does not have the right structure!");
}
#endif // WILE_DO_CHECK
if (*cp == 'a') {
var_296 = (var_296.v.pair.car ? *(var_296.v.pair.car) : LVI_NIL());
} else if (*cp == 'd') {
var_296 = (var_296.v.pair.cdr ? *(var_296.v.pair.cdr) : LVI_NIL());
} else {
wile_exception("cxr", "bld-rtl-dir/wile-rtl2-000029.scm:110", "got malformed control string '%s'", var_295.v.str);
}
}
}
lval var_297;
lval var_299[8];
var_299[0] = var_243[0];
var_299[1] = var_243[1];
var_299[2] = var_292;
var_299[3] = var_294;
var_299[4] = var_296;
var_243[0] = var_299[0];
var_243[1] = var_299[1];
var_243[2] = var_299[2];
var_243[3] = var_299[3];
var_243[4] = var_299[4];
TAIL_CALL fn_4(NULL, var_243, "bld-rtl-dir/wile-rtl2-000029.scm:110");
var_278 = var_297;
break;
}
case 4:
{
lval var_300;
#ifdef WILE_DO_CHECK
if (var_243[2].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000029.scm:111", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_300 = (var_243[2].v.pair.car ? *(var_243[2].v.pair.car) : LVI_NIL());
lval var_301;
var_301 = LVI_STRING("cadr");
lval var_302;
{
char* cp = strchr(var_301.v.str, 'r');
var_302 = var_243[2];
while (*(--cp) != 'c') {
#ifdef WILE_DO_CHECK
if (var_302.vt != LV_PAIR) {
wile_exception("cxr", "bld-rtl-dir/wile-rtl2-000029.scm:111", "input does not have the right structure!");
}
#endif // WILE_DO_CHECK
if (*cp == 'a') {
var_302 = (var_302.v.pair.car ? *(var_302.v.pair.car) : LVI_NIL());
} else if (*cp == 'd') {
var_302 = (var_302.v.pair.cdr ? *(var_302.v.pair.cdr) : LVI_NIL());
} else {
wile_exception("cxr", "bld-rtl-dir/wile-rtl2-000029.scm:111", "got malformed control string '%s'", var_301.v.str);
}
}
}
lval var_303;
var_303 = LVI_STRING("caddr");
lval var_304;
{
char* cp = strchr(var_303.v.str, 'r');
var_304 = var_243[2];
while (*(--cp) != 'c') {
#ifdef WILE_DO_CHECK
if (var_304.vt != LV_PAIR) {
wile_exception("cxr", "bld-rtl-dir/wile-rtl2-000029.scm:111", "input does not have the right structure!");
}
#endif // WILE_DO_CHECK
if (*cp == 'a') {
var_304 = (var_304.v.pair.car ? *(var_304.v.pair.car) : LVI_NIL());
} else if (*cp == 'd') {
var_304 = (var_304.v.pair.cdr ? *(var_304.v.pair.cdr) : LVI_NIL());
} else {
wile_exception("cxr", "bld-rtl-dir/wile-rtl2-000029.scm:111", "got malformed control string '%s'", var_303.v.str);
}
}
}
lval var_305;
var_305 = LVI_STRING("cadddr");
lval var_306;
{
char* cp = strchr(var_305.v.str, 'r');
var_306 = var_243[2];
while (*(--cp) != 'c') {
#ifdef WILE_DO_CHECK
if (var_306.vt != LV_PAIR) {
wile_exception("cxr", "bld-rtl-dir/wile-rtl2-000029.scm:111", "input does not have the right structure!");
}
#endif // WILE_DO_CHECK
if (*cp == 'a') {
var_306 = (var_306.v.pair.car ? *(var_306.v.pair.car) : LVI_NIL());
} else if (*cp == 'd') {
var_306 = (var_306.v.pair.cdr ? *(var_306.v.pair.cdr) : LVI_NIL());
} else {
wile_exception("cxr", "bld-rtl-dir/wile-rtl2-000029.scm:111", "got malformed control string '%s'", var_305.v.str);
}
}
}
lval var_307;
lval var_309[8];
var_309[0] = var_243[0];
var_309[1] = var_243[1];
var_309[2] = var_300;
var_309[3] = var_302;
var_309[4] = var_304;
var_309[5] = var_306;
var_243[0] = var_309[0];
var_243[1] = var_309[1];
var_243[2] = var_309[2];
var_243[3] = var_309[3];
var_243[4] = var_309[4];
var_243[5] = var_309[5];
TAIL_CALL fn_5(NULL, var_243, "bld-rtl-dir/wile-rtl2-000029.scm:111");
var_278 = var_307;
break;
}
default:
{
lval var_310;
lval var_311;
{
lptr p1 = NULL, p2 = NULL;
if (var_243[1].vt != LV_NIL) {
p1 = new_lv(LV_NIL);
*p1 = var_243[1];
}
if (var_243[2].vt != LV_NIL) {
p2 = new_lv(LV_NIL);
*p2 = var_243[2];
}
var_311 = LVI_PAIR(p1, p2);
}
var_310 = var_311;
lval var_312;
lval var_319;
lval var_320[8];
var_320[0] = LVI_PROC(fn_313,NULL,1);
var_320[1] = var_310;
var_319 = fn_1(NULL, var_320, "bld-rtl-dir/wile-rtl2-000029.scm:113");
var_312 = var_319;
lval var_322;
lval var_328;
{
lval var_329[8];
var_329[0] = LVI_PROC(fn_323,NULL,2);
var_329[1] = var_312;
var_328 = wile_foldl1(NULL, var_329, "bld-rtl-dir/wile-rtl2-000029.scm:114");
}
lval var_335;
{
lval var_336[8];
var_336[0] = LVI_PROC(fn_330,NULL,2);
var_336[1] = var_312;
var_335 = wile_foldl1(NULL, var_336, "bld-rtl-dir/wile-rtl2-000029.scm:114");
}
lval var_337;
switch (TYPE_COMBO(var_328.vt,var_335.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_337 = LVI_BOOL(var_328.v.iv != var_335.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_337 = LVI_BOOL(var_328.v.iv * var_335.v.irv.den != var_335.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_337 = LVI_BOOL(var_328.v.iv != var_335.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_337 = LVI_BOOL(var_328.v.irv.num != var_335.v.iv * var_328.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_337 = LVI_BOOL(var_328.v.irv.num * var_335.v.irv.den != var_335.v.irv.num * var_328.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_337 = LVI_BOOL(var_328.v.irv.num != var_335.v.rv * var_328.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_337 = LVI_BOOL(var_328.v.rv != var_335.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_337 = LVI_BOOL(var_328.v.rv * var_335.v.irv.den != var_335.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_337 = LVI_BOOL(var_328.v.rv != var_335.v.rv);
break;
default:
wile_exception("!=", "bld-rtl-dir/wile-rtl2-000029.scm:114", "inputs are not real-valued numbers");
break;
}
if (LV_IS_FALSE(var_337)) {
lval var_338;
var_338 = LVI_NIL();
lval var_339;
lval var_341[8];
var_341[0] = var_243[0];
var_341[1] = var_338;
var_341[2] = var_310;
var_243[0] = var_341[0];
var_243[1] = var_341[1];
var_243[2] = var_341[2];
TAIL_CALL fn_245(NULL, var_243, "bld-rtl-dir/wile-rtl2-000029.scm:116");
var_322 = var_339;
} else {
lval var_342;
var_342 = LVI_STRING("map got lists of different lengths");
lval var_343;
{
lval var_344[1];
var_344[0] = var_342;
var_343 = wile_gen_list(1, var_344, NULL);
}
if (var_343.vt == LV_PAIR && (var_343.v.pair.cdr == NULL || var_343.v.pair.cdr->vt == LV_NIL)) {
var_343 = (var_343.v.pair.car ? *(var_343.v.pair.car) : LVI_NIL());
}
cachalot->errval = new_lv(LV_NIL);
*(cachalot->errval) = var_343;
cachalot->whence = "bld-rtl-dir/wile-rtl2-000029.scm:115";
longjmp(cachalot->cenv, 1);
var_322 = var_343;
}
var_278 = var_322;
break;
}
}
return var_278;
}
// end of function wile_map
