// Generated by wile, the extremely stable scheming genius compiler

#include "wile-rtl1.h"
#include "wile-rtl2.h"

// declarations

extern lval var_argv;
extern lval var_cmd_name;
extern lval var_stdin;
extern lval var_stdout;
extern lval var_stderr;
extern lval var_pi;
extern lval var_euler_gamma;
extern lval var_show_sign;
extern lval var_int_base;
extern lval var_flt_base;
extern lval var_flt_precision;
#include "wile-rtl2.h"

// definitions

// (delta-dates y1 m1 d1 y2 m2 d2)
lval wile_delta_dates(lptr* var_1, lptr var_2)
{
lval var_4;
{
lval vs[6];
vs[0] = var_2[3];
vs[1] = var_2[4];
vs[2] = var_2[5];
var_4 = wile_julian_day(NULL, vs);
}
lval var_5;
{
lval vs[6];
vs[0] = var_2[0];
vs[1] = var_2[1];
vs[2] = var_2[2];
var_5 = wile_julian_day(NULL, vs);
}
lval var_6;
var_6 = LVI_INT(var_4.v.iv - var_5.v.iv);
return var_6;
}
// end of function wile_delta_dates
