// Generated by wile, the extremely stable scheming genius compiler

#include "wile-rtl1.h"
#include "wile-rtl2.h"

// declarations

extern lval var_argv;
extern lval var_cmd_name;
extern lval var_stdin;
extern lval var_stdout;
extern lval var_stderr;
extern lval var_pi;
extern lval var_euler_gamma;
extern lval var_show_sign;
extern lval var_int_base;
extern lval var_flt_base;
extern lval var_flt_precision;
#include "wile-rtl2.h"
static lval var_1 = LVI_BOOL(false);		// day-vec

// definitions

// @@@ (day-of-year y m d) @@@ bld-rtl-dir/wile-rtl2-000064.scm:18 @@@ wile_day_of_year @@@
lval wile_day_of_year(lptr* var_2, lptr var_3)
{
if (LV_IS_FALSE(var_1)) {
lval var_6;
var_6 = LVI_INT(0);
lval var_7;
var_7 = LVI_INT(31);
lval var_8;
var_8 = LVI_INT(59);
lval var_9;
var_9 = LVI_INT(90);
lval var_10;
var_10 = LVI_INT(120);
lval var_11;
var_11 = LVI_INT(151);
lval var_12;
var_12 = LVI_INT(181);
lval var_13;
var_13 = LVI_INT(212);
lval var_14;
var_14 = LVI_INT(243);
lval var_15;
var_15 = LVI_INT(273);
lval var_16;
var_16 = LVI_INT(304);
lval var_17;
var_17 = LVI_INT(334);
lval var_18;
{
lval vs[12];
vs[0] = var_6;
vs[1] = var_7;
vs[2] = var_8;
vs[3] = var_9;
vs[4] = var_10;
vs[5] = var_11;
vs[6] = var_12;
vs[7] = var_13;
vs[8] = var_14;
vs[9] = var_15;
vs[10] = var_16;
vs[11] = var_17;
var_18 = wile_gen_list(12, vs, NULL);
}
{
lval vs[8];
vs[0] = var_18;
var_18 = wile_list2vector(NULL, vs);
}
var_1 = var_18;
} else {
(void)
 LVI_BOOL(false);
}
lval var_20;
var_20 = LVI_INT(1);
lval var_21;
var_21 = LVI_INT(var_3[1].v.iv - var_20.v.iv);
lval var_22;
{
if (var_1.vt != LV_VECTOR) {
WILE_EX("vector-ref", "input is not a vector");
}
if (var_21.vt != LV_INT || var_21.v.iv < 0 || (size_t) var_21.v.iv >= var_1.v.vec.capa) {
WILE_EX("vector-ref", "got bad index value");
}
var_22 = var_1.v.vec.arr[var_21.v.iv] ? *(var_1.v.vec.arr[var_21.v.iv]) : LVI_NIL();
}
lval var_23;
lval var_24;
var_24 = LVI_BOOL(true);
do {
lval var_25;
var_25 = LVI_INT(2);
lval var_26;
switch (TYPE_COMBO(var_3[1].vt,var_25.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_26 = LVI_BOOL(var_3[1].v.iv > var_25.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_26 = LVI_BOOL(var_3[1].v.iv * var_25.v.irv.den > var_25.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_26 = LVI_BOOL(var_3[1].v.iv > var_25.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_26 = LVI_BOOL(var_3[1].v.irv.num > var_25.v.iv * var_3[1].v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_26 = LVI_BOOL(var_3[1].v.irv.num * var_25.v.irv.den > var_25.v.irv.num * var_3[1].v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_26 = LVI_BOOL(var_3[1].v.irv.num > var_25.v.rv * var_3[1].v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_26 = LVI_BOOL(var_3[1].v.rv > var_25.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_26 = LVI_BOOL(var_3[1].v.rv * var_25.v.irv.den > var_25.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_26 = LVI_BOOL(var_3[1].v.rv > var_25.v.rv);
break;
default:
WILE_EX(">", "inputs are not real-valued numbers");
break;
}
var_24 = var_26;
if (LV_IS_FALSE(var_24)) { break; }
lval var_27;
{
lval vs[8];
vs[0] = var_3[0];
var_27 = wile_is_leap_year(NULL, vs);
}
var_24 = var_27;
if (LV_IS_FALSE(var_24)) { break; }
} while (0);
if (LV_IS_FALSE(var_24)) {
lval var_28;
var_28 = LVI_INT(0);
var_23 = var_28;
} else {
lval var_29;
var_29 = LVI_INT(1);
var_23 = var_29;
}
lval var_30;
var_30 = LVI_INT(var_22.v.iv + var_3[2].v.iv + var_23.v.iv);
return var_30;
}
// end of function wile_day_of_year
