// Generated by wile, the extremely stable scheming genius compiler

#include "wile-rtl1.h"
#include "wile-rtl2.h"

// declarations

extern lval var_argv;
extern lval var_cmd_name;
extern lval var_stdin;
extern lval var_stdout;
extern lval var_stderr;
extern lval var_pi;
extern lval var_euler_gamma;
extern lval var_show_sign;
extern lval var_int_base;
extern lval var_flt_base;
extern lval var_flt_precision;
#include "wile-rtl2.h"
static lval fn_43(lptr*, lptr, const char*);
static lval fn_151(lptr*, lptr, const char*);

// definitions

// @@@ lambda (n) @@@ bld-rtl-dir/wile-rtl2-000086.scm:36 @@@ fn_43 @@@
static lval fn_43(lptr* var_44, lptr var_45, const char* cloc)
{
lval var_47;
lval var_49;
var_49 = LVI_BOOL(var_45[0].vt == LV_NIL);
if (!LV_IS_FALSE(var_49)) {
lval var_50;
var_50 = LVI_STRING("");
var_47 = var_50;
goto lbl_48;
}
lval var_51;
var_51 = LVI_BOOL(var_45[0].vt == LV_STRING);
if (!LV_IS_FALSE(var_51)) {
var_47 = var_45[0];
goto lbl_48;
}
lval var_52;
var_52 = LVI_BOOL(var_45[0].vt == LV_SYMBOL);
if (!LV_IS_FALSE(var_52)) {
lval var_53;
var_53 = LVI_STRING(var_45[0].v.str);
var_47 = var_53;
goto lbl_48;
}
lval var_54;
var_54 = LVI_BOOL(var_45[0].vt == LV_BOOL);
if (!LV_IS_FALSE(var_54)) {
lval var_55;
if (LV_IS_FALSE(var_45[0])) {
lval var_56;
var_56 = LVI_STRING("#f");
var_55 = var_56;
} else {
lval var_57;
var_57 = LVI_STRING("#t");
var_55 = var_57;
}
var_47 = var_55;
goto lbl_48;
}
lval var_58;
var_58 = LVI_BOOL(var_45[0].vt == LV_CMPLX || var_45[0].vt == LV_REAL || var_45[0].vt == LV_RAT || var_45[0].vt == LV_INT);
if (!LV_IS_FALSE(var_58)) {
lval var_59;
var_59 = wile_num2string(var_45[0], 10, INT_MIN, "bld-rtl-dir/wile-rtl2-000086.scm:41");
var_47 = var_59;
goto lbl_48;
}
lval var_60;
var_60 = LVI_STRING("%v");
lval var_61;
{
lval var_63[1];
var_63[0] = var_45[0];
var_61 = wile_gen_list(1, var_63, NULL);
}
{
lval var_62[8];
var_62[0] = var_60;
var_62[1] = var_61;
var_61 = wile_sprintf(NULL, var_62, "bld-rtl-dir/wile-rtl2-000086.scm:42");
}
var_47 = var_61;
lbl_48:;
return var_47;
}
// end of lambda fn_43

// @@@ max/i @@@ bld-rtl-dir/wile-rtl2-000086.scm:57 @@@ fn_133 @@@
static lval fn_133(lptr* var_134, lptr var_135, const char* cloc)
{
lval var_137;
var_137 = LVI_INT((var_135[0].v.iv > var_135[1].v.iv) ? var_135[0].v.iv : var_135[1].v.iv);
return var_137;
}
// end of prim fn_133

// @@@ string-length @@@ bld-rtl-dir/wile-rtl2-000086.scm:57 @@@ fn_139 @@@
static lval fn_139(lptr* var_140, lptr var_141, const char* cloc)
{
lval var_143;
#ifdef WILE_DO_CHECK
if (var_141[0].vt != LV_STRING) {
wile_exception("string-length", "bld-rtl-dir/wile-rtl2-000086.scm:57", "input is not a string");
}
#endif // WILE_DO_CHECK
var_143 = LVI_INT(strlen(var_141[0].v.str));
return var_143;
}
// end of prim fn_139

// @@@ lambda (s) @@@ bld-rtl-dir/wile-rtl2-000086.scm:58 @@@ fn_151 @@@
static lval fn_151(lptr* var_152, lptr var_153, const char* cloc)
{
lval var_155;
var_155 = LVI_CHAR(32);
lval var_156;
{
lval var_157[8];
var_157[0] = var_153[0];
var_157[1] = var_155;
var_157[2] = V_CLOS(var_152,0);
var_156 = wile_string_pad_left(NULL, var_157, "bld-rtl-dir/wile-rtl2-000086.scm:58");
}
return var_156;
}
// end of lambda fn_151

// @@@ string-join-by @@@ bld-rtl-dir/wile-rtl2-000086.scm:69 @@@ fn_204 @@@
static lval fn_204(lptr* var_205, lptr var_206, const char* cloc)
{
lval var_208;
var_208 = var_206[1];
{
lval var_209[8];
var_209[0] = var_206[0];
var_209[1] = var_208;
var_208 = wile_string_join_by(NULL, var_209, "bld-rtl-dir/wile-rtl2-000086.scm:69");
}
return var_208;
}
// end of prim fn_204

// @@@ (matrix-print-banded mat n-rc kl ku) @@@ bld-rtl-dir/wile-rtl2-000086.scm:28 @@@ wile_matrix_print_banded @@@
lval wile_matrix_print_banded(lptr* var_1, lptr var_2, const char* cloc)
{
lval var_5;
var_5 = LVI_BOOL(var_2[0].vt == LV_VECTOR);
if (LV_IS_FALSE(var_5)) {
lval var_6;
var_6 = LVI_STRING("matrix-print-banded: input is not a vector!");
lval var_7;
{
lval var_8[1];
var_8[0] = var_6;
var_7 = wile_gen_list(1, var_8, NULL);
}
if (var_7.vt == LV_PAIR && (var_7.v.pair.cdr == NULL || var_7.v.pair.cdr->vt == LV_NIL)) {
var_7 = (var_7.v.pair.car ? *(var_7.v.pair.car) : LVI_NIL());
}
cachalot->errval = new_lv(LV_NIL);
*(cachalot->errval) = var_7;
cachalot->whence = "bld-rtl-dir/wile-rtl2-000086.scm:30";
longjmp(cachalot->cenv, 1);
} else {
}
lval var_11;
var_11 = LVI_BOOL(true);
lval var_13;
var_13 = LVI_INT(0);
lval var_14;
switch (TYPE_COMBO(var_2[1].vt,var_13.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_14 = LVI_BOOL(var_2[1].v.iv > var_13.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_14 = LVI_BOOL(var_2[1].v.iv * var_13.v.irv.den > var_13.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_14 = LVI_BOOL(var_2[1].v.iv > var_13.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_14 = LVI_BOOL(var_2[1].v.irv.num > var_13.v.iv * var_2[1].v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_14 = LVI_BOOL(var_2[1].v.irv.num * var_13.v.irv.den > var_13.v.irv.num * var_2[1].v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_14 = LVI_BOOL(var_2[1].v.irv.num > var_13.v.rv * var_2[1].v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_14 = LVI_BOOL(var_2[1].v.rv > var_13.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_14 = LVI_BOOL(var_2[1].v.rv * var_13.v.irv.den > var_13.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_14 = LVI_BOOL(var_2[1].v.rv > var_13.v.rv);
break;
default:
wile_exception(">", "bld-rtl-dir/wile-rtl2-000086.scm:31", "inputs are not real-valued numbers");
break;
}
var_11 = var_14;
if (LV_IS_FALSE(var_11)) {
goto lbl_12;
}
lval var_15;
var_15 = LVI_INT(0);
lval var_16;
switch (TYPE_COMBO(var_2[2].vt,var_15.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_16 = LVI_BOOL(var_2[2].v.iv >= var_15.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_16 = LVI_BOOL(var_2[2].v.iv * var_15.v.irv.den >= var_15.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_16 = LVI_BOOL(var_2[2].v.iv >= var_15.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_16 = LVI_BOOL(var_2[2].v.irv.num >= var_15.v.iv * var_2[2].v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_16 = LVI_BOOL(var_2[2].v.irv.num * var_15.v.irv.den >= var_15.v.irv.num * var_2[2].v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_16 = LVI_BOOL(var_2[2].v.irv.num >= var_15.v.rv * var_2[2].v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_16 = LVI_BOOL(var_2[2].v.rv >= var_15.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_16 = LVI_BOOL(var_2[2].v.rv * var_15.v.irv.den >= var_15.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_16 = LVI_BOOL(var_2[2].v.rv >= var_15.v.rv);
break;
default:
wile_exception(">=", "bld-rtl-dir/wile-rtl2-000086.scm:31", "inputs are not real-valued numbers");
break;
}
var_11 = var_16;
if (LV_IS_FALSE(var_11)) {
goto lbl_12;
}
lval var_17;
switch (TYPE_COMBO(var_2[2].vt,var_2[1].vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_17 = LVI_BOOL(var_2[2].v.iv < var_2[1].v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_17 = LVI_BOOL(var_2[2].v.iv * var_2[1].v.irv.den < var_2[1].v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_17 = LVI_BOOL(var_2[2].v.iv < var_2[1].v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_17 = LVI_BOOL(var_2[2].v.irv.num < var_2[1].v.iv * var_2[2].v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_17 = LVI_BOOL(var_2[2].v.irv.num * var_2[1].v.irv.den < var_2[1].v.irv.num * var_2[2].v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_17 = LVI_BOOL(var_2[2].v.irv.num < var_2[1].v.rv * var_2[2].v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_17 = LVI_BOOL(var_2[2].v.rv < var_2[1].v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_17 = LVI_BOOL(var_2[2].v.rv * var_2[1].v.irv.den < var_2[1].v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_17 = LVI_BOOL(var_2[2].v.rv < var_2[1].v.rv);
break;
default:
wile_exception("<", "bld-rtl-dir/wile-rtl2-000086.scm:31", "inputs are not real-valued numbers");
break;
}
var_11 = var_17;
if (LV_IS_FALSE(var_11)) {
goto lbl_12;
}
lval var_18;
var_18 = LVI_INT(0);
lval var_19;
switch (TYPE_COMBO(var_2[3].vt,var_18.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_19 = LVI_BOOL(var_2[3].v.iv >= var_18.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_19 = LVI_BOOL(var_2[3].v.iv * var_18.v.irv.den >= var_18.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_19 = LVI_BOOL(var_2[3].v.iv >= var_18.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_19 = LVI_BOOL(var_2[3].v.irv.num >= var_18.v.iv * var_2[3].v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_19 = LVI_BOOL(var_2[3].v.irv.num * var_18.v.irv.den >= var_18.v.irv.num * var_2[3].v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_19 = LVI_BOOL(var_2[3].v.irv.num >= var_18.v.rv * var_2[3].v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_19 = LVI_BOOL(var_2[3].v.rv >= var_18.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_19 = LVI_BOOL(var_2[3].v.rv * var_18.v.irv.den >= var_18.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_19 = LVI_BOOL(var_2[3].v.rv >= var_18.v.rv);
break;
default:
wile_exception(">=", "bld-rtl-dir/wile-rtl2-000086.scm:31", "inputs are not real-valued numbers");
break;
}
var_11 = var_19;
if (LV_IS_FALSE(var_11)) {
goto lbl_12;
}
lval var_20;
switch (TYPE_COMBO(var_2[3].vt,var_2[1].vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_20 = LVI_BOOL(var_2[3].v.iv < var_2[1].v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_20 = LVI_BOOL(var_2[3].v.iv * var_2[1].v.irv.den < var_2[1].v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_20 = LVI_BOOL(var_2[3].v.iv < var_2[1].v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_20 = LVI_BOOL(var_2[3].v.irv.num < var_2[1].v.iv * var_2[3].v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_20 = LVI_BOOL(var_2[3].v.irv.num * var_2[1].v.irv.den < var_2[1].v.irv.num * var_2[3].v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_20 = LVI_BOOL(var_2[3].v.irv.num < var_2[1].v.rv * var_2[3].v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_20 = LVI_BOOL(var_2[3].v.rv < var_2[1].v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_20 = LVI_BOOL(var_2[3].v.rv * var_2[1].v.irv.den < var_2[1].v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_20 = LVI_BOOL(var_2[3].v.rv < var_2[1].v.rv);
break;
default:
wile_exception("<", "bld-rtl-dir/wile-rtl2-000086.scm:31", "inputs are not real-valued numbers");
break;
}
var_11 = var_20;
if (LV_IS_FALSE(var_11)) {
goto lbl_12;
}
lbl_12:;
if (LV_IS_FALSE(var_11)) {
lval var_21;
var_21 = LVI_STRING("matrix-print-banded: bad matrix dimensions!");
lval var_22;
{
lval var_23[4];
var_23[0] = var_21;
var_23[1] = var_2[1];
var_23[2] = var_2[2];
var_23[3] = var_2[3];
var_22 = wile_gen_list(4, var_23, NULL);
}
lval var_24;
{
lval var_25[1];
var_25[0] = var_22;
var_24 = wile_gen_list(1, var_25, NULL);
}
if (var_24.vt == LV_PAIR && (var_24.v.pair.cdr == NULL || var_24.v.pair.cdr->vt == LV_NIL)) {
var_24 = (var_24.v.pair.car ? *(var_24.v.pair.car) : LVI_NIL());
}
cachalot->errval = new_lv(LV_NIL);
*(cachalot->errval) = var_24;
cachalot->whence = "bld-rtl-dir/wile-rtl2-000086.scm:32";
longjmp(cachalot->cenv, 1);
} else {
}
lval var_28;
{
if (var_2[0].vt == LV_VECTOR) {
var_28 = LVI_INT(var_2[0].v.vec.capa);
} else if (var_2[0].vt == LV_BVECTOR) {
var_28 = LVI_INT(var_2[0].v.bvec.capa);
} else {
wile_exception("vector-length", "bld-rtl-dir/wile-rtl2-000086.scm:33", "input is not a vector");
}
}
lval var_29;
var_29 = LVI_INT(1);
lval var_30;
{
lval var_32[3];
var_32[0] = var_2[2];
var_32[1] = var_2[3];
var_32[2] = var_29;
var_30 = wile_gen_list(3, var_32, NULL);
}
{
lval var_31[8];
var_31[0] = var_30;
var_30 = wile_add(NULL, var_31, "bld-rtl-dir/wile-rtl2-000086.scm:33");
}
lval var_33;
var_33 = LVI_INT(var_30.v.iv * var_2[1].v.iv);
lval var_34;
switch (TYPE_COMBO(var_28.vt,var_33.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_34 = LVI_BOOL(var_28.v.iv >= var_33.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_34 = LVI_BOOL(var_28.v.iv * var_33.v.irv.den >= var_33.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_34 = LVI_BOOL(var_28.v.iv >= var_33.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_34 = LVI_BOOL(var_28.v.irv.num >= var_33.v.iv * var_28.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_34 = LVI_BOOL(var_28.v.irv.num * var_33.v.irv.den >= var_33.v.irv.num * var_28.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_34 = LVI_BOOL(var_28.v.irv.num >= var_33.v.rv * var_28.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_34 = LVI_BOOL(var_28.v.rv >= var_33.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_34 = LVI_BOOL(var_28.v.rv * var_33.v.irv.den >= var_33.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_34 = LVI_BOOL(var_28.v.rv >= var_33.v.rv);
break;
default:
wile_exception(">=", "bld-rtl-dir/wile-rtl2-000086.scm:33", "inputs are not real-valued numbers");
break;
}
if (LV_IS_FALSE(var_34)) {
lval var_35;
var_35 = LVI_STRING("matrix-print-banded: matrix is not big enough!");
lval var_36;
{
if (var_2[0].vt == LV_VECTOR) {
var_36 = LVI_INT(var_2[0].v.vec.capa);
} else if (var_2[0].vt == LV_BVECTOR) {
var_36 = LVI_INT(var_2[0].v.bvec.capa);
} else {
wile_exception("vector-length", "bld-rtl-dir/wile-rtl2-000086.scm:35", "input is not a vector");
}
}
lval var_37;
{
lval var_38[5];
var_38[0] = var_35;
var_38[1] = var_36;
var_38[2] = var_2[2];
var_38[3] = var_2[3];
var_38[4] = var_2[1];
var_37 = wile_gen_list(5, var_38, NULL);
}
lval var_39;
{
lval var_40[1];
var_40[0] = var_37;
var_39 = wile_gen_list(1, var_40, NULL);
}
if (var_39.vt == LV_PAIR && (var_39.v.pair.cdr == NULL || var_39.v.pair.cdr->vt == LV_NIL)) {
var_39 = (var_39.v.pair.car ? *(var_39.v.pair.car) : LVI_NIL());
}
cachalot->errval = new_lv(LV_NIL);
*(cachalot->errval) = var_39;
cachalot->whence = "bld-rtl-dir/wile-rtl2-000086.scm:34";
longjmp(cachalot->cenv, 1);
} else {
}
lval var_42;
MK_CLOS(var_44,0);
lval var_64;
var_64 = LVI_NIL();
{
lval var_65[8];
var_65[0] = LVI_PROC(fn_43,var_44,1);
var_65[1] = var_2[0];
var_65[2] = var_64;
var_64 = wile_vector_map(NULL, var_65, "bld-rtl-dir/wile-rtl2-000086.scm:36");
}
var_42 = var_64;
lval var_66;
lval var_67;
var_67 = LVI_INT(var_2[2].v.iv + var_2[3].v.iv);
var_66 = var_67;
lval var_68;
lval var_69;
var_69 = LVI_INT(1);
lval var_70;
var_70 = LVI_INT(var_66.v.iv + var_69.v.iv);
var_68 = var_70;
lval var_71;
lval var_72;
var_72 = LVI_INT(var_68.v.iv * var_2[1].v.iv);
lval var_73;
var_73 = LVI_INT(1);
lval var_74;
var_74 = LVI_INT(var_72.v.iv - var_73.v.iv);
var_71 = var_74;
lval var_79;
lval var_80;
lval var_81;
var_81 = LVI_INT(0);
var_79 = var_81;
lptr var_82 = new_lv(VT_UNINIT);
var_82->v.pair.car = &(var_79);
lbl_77:
lval var_83;
switch (TYPE_COMBO(var_79.vt,var_2[3].vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_83 = LVI_BOOL(var_79.v.iv >= var_2[3].v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_83 = LVI_BOOL(var_79.v.iv * var_2[3].v.irv.den >= var_2[3].v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_83 = LVI_BOOL(var_79.v.iv >= var_2[3].v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_83 = LVI_BOOL(var_79.v.irv.num >= var_2[3].v.iv * var_79.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_83 = LVI_BOOL(var_79.v.irv.num * var_2[3].v.irv.den >= var_2[3].v.irv.num * var_79.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_83 = LVI_BOOL(var_79.v.irv.num >= var_2[3].v.rv * var_79.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_83 = LVI_BOOL(var_79.v.rv >= var_2[3].v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_83 = LVI_BOOL(var_79.v.rv * var_2[3].v.irv.den >= var_2[3].v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_83 = LVI_BOOL(var_79.v.rv >= var_2[3].v.rv);
break;
default:
wile_exception(">=", "bld-rtl-dir/wile-rtl2-000086.scm:48", "inputs are not real-valued numbers");
break;
}
if (!LV_IS_FALSE(var_83)) {
(void)
 LVI_BOOL(true);
goto lbl_78;
}
lval var_88;
lval var_89;
lval var_90;
var_90 = LVI_INT(0);
var_88 = var_90;
lptr var_91 = new_lv(VT_UNINIT);
var_91->v.pair.car = &(var_88);
lbl_86:
lval var_92;
var_92 = LVI_INT(var_2[3].v.iv - var_79.v.iv);
lval var_93;
switch (TYPE_COMBO(var_88.vt,var_92.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_93 = LVI_BOOL(var_88.v.iv >= var_92.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_93 = LVI_BOOL(var_88.v.iv * var_92.v.irv.den >= var_92.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_93 = LVI_BOOL(var_88.v.iv >= var_92.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_93 = LVI_BOOL(var_88.v.irv.num >= var_92.v.iv * var_88.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_93 = LVI_BOOL(var_88.v.irv.num * var_92.v.irv.den >= var_92.v.irv.num * var_88.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_93 = LVI_BOOL(var_88.v.irv.num >= var_92.v.rv * var_88.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_93 = LVI_BOOL(var_88.v.rv >= var_92.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_93 = LVI_BOOL(var_88.v.rv * var_92.v.irv.den >= var_92.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_93 = LVI_BOOL(var_88.v.rv >= var_92.v.rv);
break;
default:
wile_exception(">=", "bld-rtl-dir/wile-rtl2-000086.scm:50", "inputs are not real-valued numbers");
break;
}
if (!LV_IS_FALSE(var_93)) {
(void)
 LVI_BOOL(true);
goto lbl_87;
}
lval var_95;
var_95 = LVI_INT(var_79.v.iv * var_68.v.iv);
lval var_96;
var_96 = LVI_INT(var_88.v.iv + var_95.v.iv);
lval var_97;
var_97 = LVI_STRING("");
#ifdef WILE_DO_CHECK
if (var_42.vt != LV_VECTOR) {
wile_exception("vector-set!", "bld-rtl-dir/wile-rtl2-000086.scm:51", "input is not a vector");
}
if (var_96.vt != LV_INT || var_96.v.iv < 0 || (size_t) var_96.v.iv >= var_42.v.vec.capa) {
wile_exception("vector-set!", "bld-rtl-dir/wile-rtl2-000086.scm:51", "got bad index value");
}
#endif // WILE_DO_CHECK
var_42.v.vec.arr[var_96.v.iv] = new_lv(LV_NIL);
*(var_42.v.vec.arr[var_96.v.iv]) = var_97;
lval var_99;
var_99 = LVI_INT(1);
lval var_100;
var_100 = LVI_INT(var_88.v.iv + var_99.v.iv);
var_89 = var_100;
var_88 = var_89;
goto lbl_86;
lbl_87:;
*var_91 = var_88;
lval var_101;
var_101 = LVI_INT(1);
lval var_102;
var_102 = LVI_INT(var_79.v.iv + var_101.v.iv);
var_80 = var_102;
var_79 = var_80;
goto lbl_77;
lbl_78:;
*var_82 = var_79;
lval var_107;
lval var_108;
lval var_109;
var_109 = LVI_INT(0);
var_107 = var_109;
lptr var_110 = new_lv(VT_UNINIT);
var_110->v.pair.car = &(var_107);
lbl_105:
lval var_111;
switch (TYPE_COMBO(var_107.vt,var_2[2].vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_111 = LVI_BOOL(var_107.v.iv >= var_2[2].v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_111 = LVI_BOOL(var_107.v.iv * var_2[2].v.irv.den >= var_2[2].v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_111 = LVI_BOOL(var_107.v.iv >= var_2[2].v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_111 = LVI_BOOL(var_107.v.irv.num >= var_2[2].v.iv * var_107.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_111 = LVI_BOOL(var_107.v.irv.num * var_2[2].v.irv.den >= var_2[2].v.irv.num * var_107.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_111 = LVI_BOOL(var_107.v.irv.num >= var_2[2].v.rv * var_107.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_111 = LVI_BOOL(var_107.v.rv >= var_2[2].v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_111 = LVI_BOOL(var_107.v.rv * var_2[2].v.irv.den >= var_2[2].v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_111 = LVI_BOOL(var_107.v.rv >= var_2[2].v.rv);
break;
default:
wile_exception(">=", "bld-rtl-dir/wile-rtl2-000086.scm:53", "inputs are not real-valued numbers");
break;
}
if (!LV_IS_FALSE(var_111)) {
(void)
 LVI_BOOL(true);
goto lbl_106;
}
lval var_116;
lval var_117;
lval var_118;
var_118 = LVI_INT(0);
var_116 = var_118;
lptr var_119 = new_lv(VT_UNINIT);
var_119->v.pair.car = &(var_116);
lbl_114:
lval var_120;
var_120 = LVI_INT(var_2[2].v.iv - var_107.v.iv);
lval var_121;
switch (TYPE_COMBO(var_116.vt,var_120.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_121 = LVI_BOOL(var_116.v.iv >= var_120.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_121 = LVI_BOOL(var_116.v.iv * var_120.v.irv.den >= var_120.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_121 = LVI_BOOL(var_116.v.iv >= var_120.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_121 = LVI_BOOL(var_116.v.irv.num >= var_120.v.iv * var_116.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_121 = LVI_BOOL(var_116.v.irv.num * var_120.v.irv.den >= var_120.v.irv.num * var_116.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_121 = LVI_BOOL(var_116.v.irv.num >= var_120.v.rv * var_116.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_121 = LVI_BOOL(var_116.v.rv >= var_120.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_121 = LVI_BOOL(var_116.v.rv * var_120.v.irv.den >= var_120.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_121 = LVI_BOOL(var_116.v.rv >= var_120.v.rv);
break;
default:
wile_exception(">=", "bld-rtl-dir/wile-rtl2-000086.scm:55", "inputs are not real-valued numbers");
break;
}
if (!LV_IS_FALSE(var_121)) {
(void)
 LVI_BOOL(true);
goto lbl_115;
}
lval var_123;
var_123 = LVI_INT(var_107.v.iv * var_68.v.iv);
lval var_124;
var_124 = LVI_INT(var_116.v.iv + var_123.v.iv);
lval var_125;
var_125 = LVI_INT(var_71.v.iv - var_124.v.iv);
lval var_126;
var_126 = LVI_STRING("");
#ifdef WILE_DO_CHECK
if (var_42.vt != LV_VECTOR) {
wile_exception("vector-set!", "bld-rtl-dir/wile-rtl2-000086.scm:56", "input is not a vector");
}
if (var_125.vt != LV_INT || var_125.v.iv < 0 || (size_t) var_125.v.iv >= var_42.v.vec.capa) {
wile_exception("vector-set!", "bld-rtl-dir/wile-rtl2-000086.scm:56", "got bad index value");
}
#endif // WILE_DO_CHECK
var_42.v.vec.arr[var_125.v.iv] = new_lv(LV_NIL);
*(var_42.v.vec.arr[var_125.v.iv]) = var_126;
lval var_128;
var_128 = LVI_INT(1);
lval var_129;
var_129 = LVI_INT(var_116.v.iv + var_128.v.iv);
var_117 = var_129;
var_116 = var_117;
goto lbl_114;
lbl_115:;
*var_119 = var_116;
lval var_130;
var_130 = LVI_INT(1);
lval var_131;
var_131 = LVI_INT(var_107.v.iv + var_130.v.iv);
var_108 = var_131;
var_107 = var_108;
goto lbl_105;
lbl_106:;
*var_110 = var_107;
lval var_132;
lval var_138;
var_138 = LVI_INT(0);
lval var_144;
{
lval var_145[8];
var_145[0] = var_42;
var_144 = wile_vector2list(NULL, var_145, "bld-rtl-dir/wile-rtl2-000086.scm:57");
}
lval var_146;
var_146 = LVI_NIL();
{
lval var_147[8];
var_147[0] = LVI_PROC(fn_139,NULL,1);
var_147[1] = var_144;
var_147[2] = var_146;
var_146 = wile_map(NULL, var_147, "bld-rtl-dir/wile-rtl2-000086.scm:57");
}
lval var_148;
{
lval var_149[8];
var_149[0] = LVI_PROC(fn_133,NULL,2);
var_149[1] = var_138;
var_149[2] = var_146;
var_148 = wile_foldl(NULL, var_149, "bld-rtl-dir/wile-rtl2-000086.scm:57");
}
var_132 = var_148;
lval var_150;
MK_CLOS(var_152,1);
lptr var_158 = new_lv(VT_UNINIT);
var_158->v.pair.car = &(var_132);
P_CLOS(var_152,0) = var_158;
var_150 = LVI_PROC(fn_151,var_152,1);
lval var_159;
lval var_160;
var_160 = LVI_NIL();
var_159 = var_160;
lval var_164;
lval var_165;
lval var_166;
var_166 = LVI_INT(0);
var_164 = var_166;
lval var_161;
lptr var_167 = new_lv(VT_UNINIT);
var_167->v.pair.car = &(var_164);
lbl_162:
lval var_168;
switch (TYPE_COMBO(var_164.vt,var_2[1].vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_168 = LVI_BOOL(var_164.v.iv >= var_2[1].v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_168 = LVI_BOOL(var_164.v.iv * var_2[1].v.irv.den >= var_2[1].v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_168 = LVI_BOOL(var_164.v.iv >= var_2[1].v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_168 = LVI_BOOL(var_164.v.irv.num >= var_2[1].v.iv * var_164.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_168 = LVI_BOOL(var_164.v.irv.num * var_2[1].v.irv.den >= var_2[1].v.irv.num * var_164.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_168 = LVI_BOOL(var_164.v.irv.num >= var_2[1].v.rv * var_164.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_168 = LVI_BOOL(var_164.v.rv >= var_2[1].v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_168 = LVI_BOOL(var_164.v.rv * var_2[1].v.irv.den >= var_2[1].v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_168 = LVI_BOOL(var_164.v.rv >= var_2[1].v.rv);
break;
default:
wile_exception(">=", "bld-rtl-dir/wile-rtl2-000086.scm:61", "inputs are not real-valued numbers");
break;
}
if (!LV_IS_FALSE(var_168)) {
lval var_169;
{
lval var_170[8];
var_170[0] = var_159;
var_169 = wile_list_reverse(NULL, var_170, "bld-rtl-dir/wile-rtl2-000086.scm:61");
}
var_161 = var_169;
goto lbl_163;
}
lval var_171;
lval var_172;
var_172 = LVI_STRING("");
lval var_173;
{
size_t i, capa;
if (var_2[1].vt != LV_INT || var_2[1].v.iv < 0) {
wile_exception("vector-create", "bld-rtl-dir/wile-rtl2-000086.scm:62", "expects a non-negative integer");
}
var_173.vt = LV_VECTOR;
var_173.origin = var_2[1].origin;
capa = var_2[1].v.iv;
var_173.v.vec.capa = capa;
var_173.v.vec.arr = LISP_ALLOC(lptr, (capa > 0 ? capa : 1));
for (i = 0; i < capa; ++i) {
var_173.v.vec.arr[i] = new_lv(LV_NIL);
*(var_173.v.vec.arr[i]) = var_172;
}
}
var_171 = var_173;
lval var_174;
lval var_175;
var_175 = LVI_INT(0);
lval var_176;
var_176 = LVI_INT(var_164.v.iv - var_2[2].v.iv);
lval var_177;
{
lval var_179[2];
var_179[0] = var_175;
var_179[1] = var_176;
var_177 = wile_gen_list(2, var_179, NULL);
}
{
lval var_178[8];
var_178[0] = var_177;
var_177 = wile_max(NULL, var_178, "bld-rtl-dir/wile-rtl2-000086.scm:63");
}
var_174 = var_177;
lval var_180;
lval var_181;
var_181 = LVI_INT(var_164.v.iv + var_2[3].v.iv);
lval var_182;
var_182 = LVI_INT(1);
lval var_183;
var_183 = LVI_INT(var_2[1].v.iv - var_182.v.iv);
lval var_184;
{
lval var_186[2];
var_186[0] = var_181;
var_186[1] = var_183;
var_184 = wile_gen_list(2, var_186, NULL);
}
{
lval var_185[8];
var_185[0] = var_184;
var_184 = wile_min(NULL, var_185, "bld-rtl-dir/wile-rtl2-000086.scm:64");
}
var_180 = var_184;
lval var_190;
lval var_191;
var_190 = var_174;
lptr var_192 = new_lv(VT_UNINIT);
var_192->v.pair.car = &(var_190);
lbl_188:
lval var_193;
switch (TYPE_COMBO(var_190.vt,var_180.vt)) {
case TYPE_COMBO(LV_INT,LV_INT):
var_193 = LVI_BOOL(var_190.v.iv > var_180.v.iv);
break;
case TYPE_COMBO(LV_INT,LV_RAT):
var_193 = LVI_BOOL(var_190.v.iv * var_180.v.irv.den > var_180.v.irv.num);
break;
case TYPE_COMBO(LV_INT,LV_REAL):
var_193 = LVI_BOOL(var_190.v.iv > var_180.v.rv);
break;
case TYPE_COMBO(LV_RAT,LV_INT):
var_193 = LVI_BOOL(var_190.v.irv.num > var_180.v.iv * var_190.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_RAT):
var_193 = LVI_BOOL(var_190.v.irv.num * var_180.v.irv.den > var_180.v.irv.num * var_190.v.irv.den);
break;
case TYPE_COMBO(LV_RAT,LV_REAL):
var_193 = LVI_BOOL(var_190.v.irv.num > var_180.v.rv * var_190.v.irv.den);
break;
case TYPE_COMBO(LV_REAL,LV_INT):
var_193 = LVI_BOOL(var_190.v.rv > var_180.v.iv);
break;
case TYPE_COMBO(LV_REAL,LV_RAT):
var_193 = LVI_BOOL(var_190.v.rv * var_180.v.irv.den > var_180.v.irv.num);
break;
case TYPE_COMBO(LV_REAL,LV_REAL):
var_193 = LVI_BOOL(var_190.v.rv > var_180.v.rv);
break;
default:
wile_exception(">", "bld-rtl-dir/wile-rtl2-000086.scm:66", "inputs are not real-valued numbers");
break;
}
if (!LV_IS_FALSE(var_193)) {
(void)
 LVI_BOOL(true);
goto lbl_189;
}
lval var_195;
var_195 = LVI_INT(var_190.v.iv * var_66.v.iv);
lval var_196;
var_196 = LVI_INT(var_164.v.iv + var_195.v.iv);
lval var_197;
var_197 = LVI_INT(var_2[3].v.iv + var_196.v.iv);
lval var_198;
#ifdef WILE_DO_CHECK
if (var_42.vt != LV_VECTOR) {
wile_exception("vector-ref", "bld-rtl-dir/wile-rtl2-000086.scm:67", "input is not a vector");
}
if (var_197.vt != LV_INT || var_197.v.iv < 0 || (size_t) var_197.v.iv >= var_42.v.vec.capa) {
wile_exception("vector-ref", "bld-rtl-dir/wile-rtl2-000086.scm:67", "got bad index value");
}
#endif // WILE_DO_CHECK
var_198 = var_42.v.vec.arr[var_197.v.iv] ? *(var_42.v.vec.arr[var_197.v.iv]) : LVI_NIL();
#ifdef WILE_DO_CHECK
if (var_171.vt != LV_VECTOR) {
wile_exception("vector-set!", "bld-rtl-dir/wile-rtl2-000086.scm:67", "input is not a vector");
}
if (var_190.vt != LV_INT || var_190.v.iv < 0 || (size_t) var_190.v.iv >= var_171.v.vec.capa) {
wile_exception("vector-set!", "bld-rtl-dir/wile-rtl2-000086.scm:67", "got bad index value");
}
#endif // WILE_DO_CHECK
var_171.v.vec.arr[var_190.v.iv] = new_lv(LV_NIL);
*(var_171.v.vec.arr[var_190.v.iv]) = var_198;
lval var_200;
var_200 = LVI_INT(1);
lval var_201;
var_201 = LVI_INT(var_190.v.iv + var_200.v.iv);
var_191 = var_201;
var_190 = var_191;
goto lbl_188;
lbl_189:;
*var_192 = var_190;
{
lval var_203[8];
var_203[0] = var_150;
var_203[1] = var_171;
(void)
 wile_vector_map_inplace(NULL, var_203, "bld-rtl-dir/wile-rtl2-000086.scm:68");
}
lval var_210;
var_210 = LVI_STRING(" ");
lval var_211;
{
lval var_212[8];
var_212[0] = var_171;
var_211 = wile_vector2list(NULL, var_212, "bld-rtl-dir/wile-rtl2-000086.scm:69");
}
lval var_213;
{
lval var_214[3];
var_214[0] = LVI_PROC(fn_204,NULL,-2);
var_214[1] = var_210;
var_214[2] = var_211;
var_213 = wile_gen_list(3, var_214, NULL);
}
var_213 = wile_apply_function(&(var_213), "bld-rtl-dir/wile-rtl2-000086.scm:69");
lval var_215;
{
lptr p1 = NULL, p2 = NULL;
if (var_213.vt != LV_NIL) {
p1 = new_lv(LV_NIL);
*p1 = var_213;
}
if (var_159.vt != LV_NIL) {
p2 = new_lv(LV_NIL);
*p2 = var_159;
}
var_215 = LVI_PAIR(p1, p2);
}
var_159 = var_215;
lval var_216;
var_216 = LVI_INT(1);
lval var_217;
var_217 = LVI_INT(var_164.v.iv + var_216.v.iv);
var_165 = var_217;
var_164 = var_165;
goto lbl_162;
lbl_163:;
*var_167 = var_164;
*var_158 = var_132;
return var_161;
}
// end of function wile_matrix_print_banded
