// Generated by wile, the extremely stable scheming genius compiler

#include "wile-rtl1.h"
#include "wile-rtl2.h"

// declarations

extern lval var_argv;
extern lval var_cmd_name;
extern lval var_stdin;
extern lval var_stdout;
extern lval var_stderr;
extern lval var_pi;
extern lval var_euler_gamma;
extern lval var_show_sign;
extern lval var_int_base;
extern lval var_flt_base;
extern lval var_flt_precision;
#include "wile-rtl2.h"

// definitions

// @@@ (list-drop-while drop? lst) @@@ bld-rtl-dir/wile-rtl2-000041.scm:13 @@@ wile_list_drop_while @@@
lval wile_list_drop_while(lptr* var_1, lptr var_2, const char* cloc)
{
lbl_3:;
lval var_4;
lval var_5;
var_5 = LVI_BOOL(true);
lval var_7;
var_7 = LVI_BOOL(var_2[1].vt == LV_NIL);
lval var_8;
var_8 = LVI_BOOL(LV_IS_FALSE(var_7));
var_5 = var_8;
if (LV_IS_FALSE(var_5)) {
goto lbl_6;
}
lval var_9;
#ifdef WILE_DO_CHECK
if (var_2[1].vt != LV_PAIR) {
wile_exception("car", "bld-rtl-dir/wile-rtl2-000041.scm:14", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_9 = (var_2[1].v.pair.car ? *(var_2[1].v.pair.car) : LVI_NIL());
lval var_10;
{
lval var_11[1];
var_11[0] = var_9;
var_10 = wile_gen_list(1, var_11, NULL);
}
lval var_12;
{
lval var_13[2];
var_13[0] = var_2[0];
var_13[1] = var_10;
var_12 = wile_gen_list(2, var_13, NULL);
}
var_12 = wile_apply_function(&(var_12), "bld-rtl-dir/wile-rtl2-000041.scm:14");
var_5 = var_12;
if (LV_IS_FALSE(var_5)) {
goto lbl_6;
}
lbl_6:;
if (LV_IS_FALSE(var_5)) {
var_4 = var_2[1];
} else {
lval var_14;
#ifdef WILE_DO_CHECK
if (var_2[1].vt != LV_PAIR) {
wile_exception("cdr", "bld-rtl-dir/wile-rtl2-000041.scm:15", "input is not a pair!");
}
#endif // WILE_DO_CHECK
var_14 = (var_2[1].v.pair.cdr ? *(var_2[1].v.pair.cdr) : LVI_NIL());
lval var_15;
lval var_17[8];
var_17[0] = var_2[0];
var_17[1] = var_14;
var_2[0] = var_17[0];
var_2[1] = var_17[1];
goto lbl_3;
var_4 = var_15;
}
return var_4;
}
// end of function wile_list_drop_while
