// Generated by wile, the extremely stable scheming genius compiler

#include "wile-rtl1.h"
#include "wile-rtl2.h"

// declarations

extern lval var_argv;
extern lval var_cmd_name;
extern lval var_stdin;
extern lval var_stdout;
extern lval var_stderr;
extern lval var_pi;
extern lval var_euler_gamma;
extern lval var_show_sign;
extern lval var_int_base;
extern lval var_flt_base;
extern lval var_flt_precision;
#include "wile-rtl2.h"
static lval fn_4(lptr*, lptr, const char*);

// definitions

// @@@ lambda args @@@ bld-rtl-dir/wile-rtl2-000080.scm:14 @@@ fn_4 @@@
static lval fn_4(lptr* var_5, lptr var_6, const char* cloc)
{
lval var_8;
{
lval var_9[3];
var_9[0] = V_CLOS(var_5,0);
var_9[1] = V_CLOS(var_5,1);
var_9[2] = var_6[0];
var_8 = wile_gen_list(3, var_9, NULL);
}
var_8 = wile_apply_function(&(var_8), "bld-rtl-dir/wile-rtl2-000080.scm:14");
return var_8;
}
// end of lambda fn_4

// @@@ (curry func arg1) @@@ bld-rtl-dir/wile-rtl2-000080.scm:13 @@@ wile_curry @@@
lval wile_curry(lptr* var_1, lptr var_2, const char* cloc)
{
MK_CLOS(var_5,2);
lptr var_10 = new_lv(VT_UNINIT);
var_10->v.pair.car = &(var_2[1]);
P_CLOS(var_5,1) = var_10;
lptr var_11 = new_lv(VT_UNINIT);
var_11->v.pair.car = &(var_2[0]);
P_CLOS(var_5,0) = var_11;
*var_11 = var_2[0];
*var_10 = var_2[1];
return LVI_PROC(fn_4,var_5,-1);
}
// end of function wile_curry
